import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,generate,SIZE,FLOORS,distance,lineOfSight} from '../src/engine.js';

test('100 seeds: every floor, enemy and supply is reachable; spawns do not overlap',()=>{
 for(let seed=1;seed<=100;seed++)for(let floor=1;floor<=FLOORS.length;floor++){
 const m=generate(seed,floor),seen=new Set(),queue=[m.start];
 for(let i=0;i<queue.length;i++){const a=queue[i],key=`${a.x},${a.y}`;if(seen.has(key))continue;seen.add(key);for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(m.grid[a.y+dy]?.[a.x+dx]===1&&!seen.has(`${a.x+dx},${a.y+dy}`))queue.push({x:a.x+dx,y:a.y+dy});}
 for(const o of [m.end,...m.enemies,...m.items])assert.ok(seen.has(`${o.x},${o.y}`),`unreachable ${seed}/${floor}`);
 assert.equal(new Set(m.enemies.map(e=>`${e.x},${e.y}`)).size,m.enemies.length);
 assert.equal(m.grid.flat().filter(t=>t===1).length,seen.size);
 assert.ok(!m.enemies.some(e=>distance(e,m.start)===0));
 }
});
test('walls and invalid actions cost no turn; one valid move advances exactly once',()=>{const g=new Game(123);g.enemies=[];g.player.x=2;g.player.y=2;assert.equal(g.action('move',[-1,0]),false);assert.equal(g.turn,1);assert.equal(g.action('heal'),false);assert.equal(g.turn,1);assert.equal(g.action('move',[1,0]),true);assert.equal(g.turn,2);assert.equal(g.player.x,3);});
test('firing consumes ammo, damages target and reload transfers only missing rounds',()=>{const g=new Game(123);g.enemies=[{id:'test',type:'crawler',x:g.player.x+1,y:g.player.y,hp:100,maxHp:100}];g.reveal();assert.equal(g.action('fire'),true);assert.ok(g.enemies[0].hp<100);assert.equal(g.player.ammo[0],7);assert.equal(g.player.hp,100);assert.equal(g.enemies[0].charge,true);g.action('reload');assert.equal(g.player.ammo[0],8);assert.equal(g.player.reserve,47);assert.equal(g.player.hp,89);});
test('cover blocks projectiles; ranged attacks telegraph before dealing damage',()=>{const g=new Game(12);g.barriers=[];g.grid=Array.from({length:SIZE},()=>Array(SIZE).fill(1));g.player.x=4;g.player.y=4;g.enemies=[{id:'gun',type:'gunner',x:7,y:4,hp:40,maxHp:40,alert:true,charge:false}];g.reveal();g.action('wait');assert.equal(g.player.hp,100);assert.equal(g.enemies[0].charge,true);g.grid[4][6]=0;assert.equal(lineOfSight(g.grid,g.player,g.enemies[0]),false);g.action('wait');assert.equal(g.player.hp,100);assert.equal(g.enemies[0].charge,false);});
test('experience opens a perk choice, pauses turns, and applies exactly once',()=>{const g=new Game(12);g.enemies=[];for(let i=0;i<3;i++)g.hurt({id:String(i),type:'crawler',x:1,y:1,hp:1},50);assert.equal(g.pendingPerks,1);assert.equal(g.player.level,2);assert.equal(g.action('wait'),false);g.choosePerk('damage');assert.equal(g.player.bonus,6);g.choosePerk('damage');assert.equal(g.player.bonus,6);assert.equal(g.action('wait'),true);});
test('save restores map, stats, fog, target, and pending upgrades',()=>{const g=new Game(345);g.action('fire');const loaded=Game.restore(g.serialize());assert.ok(loaded instanceof Game);assert.deepEqual(loaded.player,g.player);assert.deepEqual(loaded.grid,g.grid);assert.equal(loaded.turn,g.turn);assert.equal(Game.restore('broken'),null);});
test('floor progression preserves build and final exit requires boss defeat',()=>{const g=new Game(12);g.player.bonus=14;for(let f=1;f<FLOORS.length;f++){for(const e of g.enemies)if(e.type==='boss'||e.type==='warden')e.hp=0;g.player.x=g.end.x;g.player.y=g.end.y;assert.equal(g.action('interact'),true);assert.equal(g.floor,f+1);}assert.equal(g.player.bonus,14);g.player.x=g.end.x;g.player.y=g.end.y;assert.equal(g.action('interact'),false);g.enemies.find(e=>e.type==='boss').hp=0;assert.equal(g.action('interact'),true);assert.equal(g.status,'won');assert.equal(g.action('wait'),false);});
test('death ends actions and cannot be loaded as a live run',()=>{const g=new Game(12);g.player.hp=1;g.enemies=[{id:'killer',type:'crawler',x:g.player.x+1,y:g.player.y,hp:100,alert:true,charge:true}];g.action('wait');assert.equal(g.status,'dead');assert.equal(g.player.hp,0);assert.equal(g.action('heal'),false);assert.equal(Game.restore(g.serialize()),null);});
test('supply pickups and healing apply to the player',()=>{const g=new Game(12);g.enemies=[];g.items=[{x:g.player.x+1,y:g.player.y,type:'ammo'}];g.action('move',[1,0]);assert.equal(g.player.reserve,64);assert.equal(g.items.length,0);g.player.hp=20;g.action('heal');assert.equal(g.player.hp,65);assert.equal(g.player.meds,1);});
