import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,SIZE,FLOORS,WEAPONS,generate,reachable,key,makeEnemy,lineOfSight} from '../src/engine.js';

function arena(){const g=new Game(42);g.grid=Array.from({length:SIZE},()=>Array(SIZE).fill(1));Object.assign(g.player,{x:10,y:10});g.enemies=[];g.props=[];g.items=[];g.hazards=[];g.marks=[];g.reveal();return g;}
const cover=(x,y)=>({id:'box',type:'cover',x,y,hp:65,maxHp:65});

test('600 generated floors: cover never traps player, exit, enemies or items',()=>{
  for(let seed=1;seed<=100;seed++)for(let floor=1;floor<=FLOORS.length;floor++){
    const map=generate(seed,floor),seen=reachable(map,map.start);
    for(const o of [map.end,...map.enemies,...map.items])assert.ok(seen.has(key(o)),`${seed}/${floor}: ${o.type||'exit'} at ${key(o)} blocked`);
    assert.ok(!map.props.some(o=>o.hp>0&&key(o)===key(map.start)));
  }
});
test('screen cardinal movement uses world x/y and rejects diagonals',()=>{const g=arena();g.action('move',[0,-1]);assert.deepEqual([g.player.x,g.player.y],[10,9]);g.action('move',[1,0]);assert.deepEqual([g.player.x,g.player.y],[11,9]);g.action('move',[0,1]);g.action('move',[-1,0]);assert.deepEqual([g.player.x,g.player.y],[10,10]);assert.equal(g.action('move',[1,1]),false);assert.equal(g.turn,5);});
test('cover blocks walking and reduces ranged damage only from its protected side',()=>{const g=arena();g.props=[cover(11,10)];assert.equal(g.action('move',[1,0]),false);g.damagePlayer(20,'test',{x:14,y:10});assert.equal(g.player.hp,89);assert.ok(g.props[0].hp<65);g.damagePlayer(20,'test',{x:6,y:10});assert.equal(g.player.hp,69);});
test('cover can be targeted, destroyed, and walked through',()=>{const g=arena();g.props=[cover(11,10)];g.props[0].hp=10;g.target='box';g.action('fire');assert.ok(g.props[0].hp<=0);assert.equal(g.action('move',[1,0]),true);});
test('enemy cover and armor apply; sniper penetration increases damage',()=>{const g=arena();const e=makeEnemy('brute',14,10,'heavy');g.enemies=[e];g.props=[cover(13,10)];g.hitTarget(e,40,g.player,0);const ordinary=90-e.hp;e.hp=90;g.props[0].hp=65;g.hitTarget(e,40,g.player,.7);assert.ok(90-e.hp>ordinary);});
test('grenades preview validation is free, valid throw consumes a turn and affects radius',()=>{const g=arena();const near=makeEnemy('brute',14,10,'near'),far=makeEnemy('brute',17,10,'far');g.enemies=[near,far];assert.equal(g.action('grenade',{x:20,y:10}),false);assert.equal(g.player.grenades,2);assert.equal(g.turn,1);g.action('grenade',{x:14,y:10});assert.equal(g.player.grenades,1);assert.equal(g.turn,2);assert.ok(near.hp<90);assert.equal(far.hp,90);assert.equal(g.player.hp,100);});
test('grenades can hurt player and walls block blast propagation',()=>{const g=arena();g.action('grenade',{x:11,y:10});assert.equal(g.player.hp,55);const other=arena();for(let y=0;y<SIZE;y++)other.grid[y][11]=0;other.explode({x:12,y:10},2,55);assert.equal(other.player.hp,100);});
test('barrel chains terminate and bomber dies exactly once',()=>{const g=arena();g.props=[{id:'a',type:'barrel',x:14,y:10,hp:18},{id:'b',type:'barrel',x:15,y:10,hp:18}];const e=makeEnemy('bomber',16,10,'boom');g.enemies=[e];g.damageProp(g.props[0],20);assert.ok(g.props.every(o=>o.hp<=0));assert.ok(e.hp<=0);assert.equal(g.player.kills,1);assert.ok(g.effects.filter(e=>e.type==='blast').length<=3);});
test('pack capacity, pickup, switch and salvage keep ammo accounting',()=>{const g=arena();g.items=[{type:'weapon',weapon:2,x:10,y:10}];g.pickup();const smg=g.player.owned[2];assert.equal(g.weaponAt(smg).id,'smg');g.items=[{type:'weapon',weapon:3,x:10,y:10}];g.pickup();assert.equal(g.items.length,1);const sniper=g.items[0].slot;g.action('salvage',1);assert.equal(g.player.reserve,48);assert.equal(g.player.shell,16);assert.equal(g.player.scrap,20);g.action('takeWeapon',sniper);assert.deepEqual(g.player.owned,[0,smg,sniper]);assert.equal(g.action('weapon',sniper),true);assert.equal(g.player.weapon,sniper);assert.equal(g.action('weapon',5),false);});
test('last weapon cannot be salvaged and repeat loot remains a separate gun',()=>{const g=arena();g.player.owned=[0];assert.equal(g.action('salvage',0),false);g.items=[{type:'weapon',weapon:0,x:10,y:10}];g.pickup();assert.equal(g.player.scrap,0);assert.equal(g.player.owned.length,2);assert.notEqual(g.player.owned[0],g.player.owned[1]);assert.equal(g.weaponAt(g.player.owned[1]).id,'rifle');assert.equal(g.items.length,0);});
test('energy and rifle reserves are distinct and upgrades cap at +3',()=>{const g=arena(),slot=g.addWeapon(4);g.action('weapon',slot);g.player.ammo[slot]=0;g.action('reload');assert.equal(g.player.energy,12);assert.equal(g.player.reserve,48);g.player.scrap=200;for(let i=0;i<3;i++)assert.equal(g.action('upgrade'),true);assert.equal(g.player.scrap,80);assert.equal(g.action('upgrade'),false);assert.equal(g.weaponDamage().min,50);});
test('SMG burst fires two rounds or the final single round',()=>{const g=arena(),slot=g.addWeapon(2);g.player.weapon=slot;const e=makeEnemy('brute',14,10,'e');g.enemies=[e];g.target=e.id;g.action('fire');assert.equal(g.player.ammo[slot],16);assert.equal(g.player.stats.shots,2);g.player.ammo[slot]=1;g.action('fire');assert.equal(g.player.ammo[slot],0);assert.equal(g.player.stats.shots,3);});
test('single-use terminal transactions validate cost before spending',()=>{const g=arena();g.props=[{id:'term',x:11,y:10,type:'terminal',used:false}];assert.equal(g.action('terminal','ammo'),false);g.player.scrap=20;assert.equal(g.action('terminal','ammo'),true);assert.equal(g.player.scrap,5);assert.equal(g.player.reserve,72);g.player.scrap=50;assert.equal(g.action('terminal','ammo'),false);assert.equal(g.player.scrap,50);});
test('hazards poison; healing removes poison and hazmat protects',()=>{const g=arena();g.hazards=[{x:11,y:10,type:'acid'}];g.action('move',[1,0]);assert.equal(g.player.hp,92);assert.equal(g.player.poison,3);g.action('move',[-1,0]);assert.equal(g.player.hp,88);g.action('heal');assert.equal(g.player.poison,0);g.player.hazmat=10;g.action('move',[1,0]);assert.equal(g.player.hp,100);});
test('legacy guard aliases combined wait; a subsequent move ends its damage reduction',()=>{const g=arena();const e=makeEnemy('gunner',14,10,'e');e.alert=true;e.charge=true;e.windup=1;g.enemies=[e];g.action('guard');assert.equal(g.player.hp,93);assert.equal(g.player.focus,true);assert.equal(g.player.evasive,true);g.action('wait');assert.equal(g.player.guard,true);g.action('move',[0,1]);assert.equal(g.player.guard,false);});
test('sniper locks its old aim; moving avoids charged shot',()=>{const g=arena();const e=makeEnemy('sniper',17,10,'s');g.enemies=[e];g.reveal();g.action('wait');assert.equal(e.windup,2);g.action('move',[0,1]);g.action('wait');assert.equal(g.player.hp,100);assert.ok(g.logs.some(l=>l.text.includes('原本的位置')));});
test('boss bombardment is marked two turns in advance',()=>{const g=arena();const boss=makeEnemy('boss',15,10,'boss');boss.attackCount=1;g.enemies=[boss];g.reveal();g.action('wait');assert.equal(g.marks.length,1);assert.equal(g.marks[0].due,g.turn+2);g.action('move',[0,1]);g.action('move',[0,1]);assert.equal(g.marks.length,0);assert.ok(!g.logs.some(l=>l.text.includes('爆炸衝擊')));});
test('v1 saves migrate in place and v2 random state survives reload',()=>{const g=new Game(42),data=JSON.parse(g.serialize()).data;delete data.player.owned;delete data.player.grenades;delete data.hazards;delete data.marks;data.player.ammo=[8,4];const restored=Game.restore(JSON.stringify({version:1,data}));assert.ok(restored);assert.equal(restored.player.grenades,2);assert.deepEqual(restored.player.ammo.slice(0,WEAPONS.length),[8,4,0,0,0,0]);assert.equal(restored.floor,g.floor);const roundtrip=Game.restore(restored.serialize());assert.deepEqual(roundtrip.player,restored.player);});
test('diagonal wall corners block shots',()=>{const g=arena();g.grid[10][11]=0;g.grid[11][10]=0;assert.equal(lineOfSight(g.grid,{x:10,y:10},{x:11,y:11}),false);});
