import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {readFile,writeFile} from 'node:fs/promises';
import {validateSelection} from '../src/materials.js';
export async function compileMaterials(){
  const value=validateSelection(JSON.parse(await readFile(new URL('../art/materials/selection.json',import.meta.url),'utf8')));
  const text='// Generated by npm run materials from art/materials/selection.json.\nexport const MATERIAL_SELECTION='+JSON.stringify(value)+';\n';
  await writeFile(new URL('../src/material-selection.js',import.meta.url),text);
  return value;
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===resolve(process.argv[1])){await compileMaterials();console.log('Material selection validated and compiled.');}
