import {readFile,readdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {validateRecipe} from '../src/map-recipes.js';
export async function compileRecipes(){
  const root=new URL('../',import.meta.url),dir=new URL('maps/recipes/',root),pool=[];
  for(const file of (await readdir(dir)).filter(n=>n.endsWith('.json')).sort())pool.push(validateRecipe(JSON.parse(await readFile(new URL(file,dir),'utf8'))));
  if(new Set(pool.map(r=>r.id)).size!==pool.length)throw new Error('Duplicate recipe id');
  const text='// Generated by npm run recipes from maps/recipes/*.json. Do not edit.\nexport const MAP_RECIPES='+JSON.stringify(pool,null,2)+';\n';
  const output=new URL('src/map-recipes-data.js',root);
  if(await readFile(output,'utf8').catch(()=>null)!==text)await writeFile(output,text);
  return pool;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(`Compiled ${(await compileRecipes()).length} map recipes`);
