import {readdir,readFile,writeFile} from 'node:fs/promises';
import {resolve,basename} from 'node:path';
import {pathToFileURL} from 'node:url';
const root=resolve(import.meta.dirname,'..');
export const STORY_BODY_LIMIT=12000;
const fail=(file,line,fix)=>{throw Error(`${file}:${line}: ${fix}`);};
export function parseStory(text,file,{retired=[],banned=[]}={}){
 const lines=text.replaceAll('\r','').split('\n'),end=lines.indexOf('---',1),meta={},locations={};
 if(lines[0]!=='---'||end<0)fail(file,1,'請用 --- 包住開頭的 front matter。');
 for(let i=1;i<end;i++){
  const m=/^([a-z]+):\s*(.*?)\s*$/.exec(lines[i]);if(!m)fail(file,i+1,'請使用「欄位: 值」。');
  if(!['id','title','faction','floors','price','order'].includes(m[1])||m[1] in meta)fail(file,i+1,'請移除未知或重複欄位。');
  meta[m[1]]=m[2];locations[m[1]]=i+1;
 }
 const error=(k,msg)=>fail(file,locations[k]||2,msg);
 if(!/^[a-z][a-z0-9-]*$/.test(meta.id||'')||meta.id!==basename(file,'.md'))error('id','請填入與檔名相同的英文小寫 id（可含數字及 -）。');
 if(['soldier','recon','engineer','necromancer','druid','bulwark','berserker','ninja'].includes(meta.id))error('id','ID 與職業重複，請更換故事檔名與 id。');
 if(retired.includes(meta.id))error('id','此 ID 已停用，請使用全新的檔名與 id。');
 if(!meta.title?.trim())error('title','請填寫 title。');
 if(!['any','legacy','loyalist','rebel','swarm'].includes(meta.faction||'any'))error('faction','faction 請填 any、legacy、loyalist、rebel 或 swarm。');
 const range=/^([1-6])(?:-([1-6]))?$/.exec(meta.floors||'1-6');if(!range||Number(range[1])>Number(range[2]||range[1]))error('floors','floors 請填 1–6 內的單一樓層或遞增範圍，例如 3 或 1-6。');
 for(const k of ['price','order'])if(meta[k]!==undefined&&(!/^\d+$/.test(meta[k])||!Number.isSafeInteger(Number(meta[k]))))error(k,`${k} 請填非負整數。`);
 const body=lines.slice(end+1).join('\n').trim();if(!body||body.length>STORY_BODY_LIMIT)fail(file,end+2,`內文請填 1–${STORY_BODY_LIMIT} 字。`);
 for(let i=0;i<lines.length;i++)for(const word of banned)if(lines[i].toLocaleLowerCase().includes(word.toLocaleLowerCase()))fail(file,i+1,`請移除禁用詞「${word}」，或請內容負責人調整 _banned-words.txt。`);
 return {id:meta.id,title:meta.title,faction:meta.faction||'any',floors:[Number(range[1]),Number(range[2]||range[1])],price:Number(meta.price??100),order:Number(meta.order??0),body};
}
export async function compileStories({directory=resolve(root,'content/stories'),output=resolve(root,'src/story-data.js'),check=false}={}){
 const list=async name=>(await readFile(resolve(directory,name),'utf8')).split(/\r?\n/).map(s=>s.trim()).filter(s=>s&&!s.startsWith('#'));
 const retired=await list('_retired.txt'),banned=await list('_banned-words.txt'),entries=[],ids=new Set();
 for(const name of (await readdir(directory)).sort())if(name.endsWith('.md')&&name!=='README.md'){
  const file=resolve(directory,name),entry=parseStory(await readFile(file,'utf8'),name,{retired,banned});if(ids.has(entry.id))fail(name,2,'ID 重複，請改成未使用的 ID。');ids.add(entry.id);entries.push(entry);
 }
 let old='';try{old=await readFile(output,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;}
 const oldRetired=/export const RETIRED_STORY_IDS=(.*);/.exec(old);for(const id of oldRetired?JSON.parse(oldRetired[1]):[])if(!retired.includes(id))fail('_retired.txt',1,`請保留已停用 ID ${id}，避免重用舊玩家的解鎖識別字。`);
 const prior=/export const STORY_IDS=(.*);/.exec(old);for(const id of prior?JSON.parse(prior[1]):[])if(!ids.has(id)&&!retired.includes(id))fail('_retired.txt',1,`故事 ${id} 已刪除，請將 ID 加入停用清單，或還原 ${id}.md。`);
 entries.sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id,'en'));
 const generated=`// Generated by npm run stories. Do not edit.\nexport const STORY_IDS=${JSON.stringify([...ids].sort())};\nexport const RETIRED_STORY_IDS=${JSON.stringify([...new Set(retired)].sort())};\nexport const STORIES=${JSON.stringify(entries,null,2)};\n`;
 if(check&&old!==generated)fail('src/story-data.js',1,'產生檔過期，請執行 npm run stories 並提交結果。');
 if(!check&&old!==generated)await writeFile(output,generated);return entries;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)await compileStories({check:process.argv.includes('--check')});
