// Generated by npm run stories. Do not edit.
export const STORY_IDS=["infiltrator-roster","loyalist-batch","loyalist-manifest","loyalist-sealed","loyalist-standby","loyalist-survey","loyalist-wake","rebel-articles","rebel-interrogation","rebel-last-call","rebel-missing","rebel-roster","rebel-takeover","rift-catalogue","rift-inscription","rift-last-inscription","swarm-breach","swarm-culture-first","swarm-culture-seventh","swarm-fragment","swarm-notes","swarm-sample-b7"];
export const RETIRED_STORY_IDS=["core-response","evacuation-cancelled","final-protocol","research-record","sealed-orders","unlisted-signal"];
export const STORIES=[
  {
    "id": "loyalist-standby",
    "title": "ENCRYPTED",
    "faction": "loyalist",
    "floors": [
      1,
      1
    ],
    "price": 100,
    "order": 101,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "loyalist-survey",
    "title": "ENCRYPTED",
    "faction": "loyalist",
    "floors": [
      2,
      2
    ],
    "price": 100,
    "order": 102,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "loyalist-manifest",
    "title": "ENCRYPTED",
    "faction": "loyalist",
    "floors": [
      3,
      3
    ],
    "price": 100,
    "order": 103,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "loyalist-batch",
    "title": "ENCRYPTED",
    "faction": "loyalist",
    "floors": [
      4,
      4
    ],
    "price": 100,
    "order": 104,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "loyalist-sealed",
    "title": "ENCRYPTED",
    "faction": "loyalist",
    "floors": [
      5,
      5
    ],
    "price": 100,
    "order": 105,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "loyalist-wake",
    "title": "ENCRYPTED",
    "faction": "loyalist",
    "floors": [
      6,
      6
    ],
    "price": 100,
    "order": 106,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rebel-takeover",
    "title": "ENCRYPTED",
    "faction": "rebel",
    "floors": [
      1,
      1
    ],
    "price": 100,
    "order": 201,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rebel-missing",
    "title": "ENCRYPTED",
    "faction": "rebel",
    "floors": [
      2,
      2
    ],
    "price": 100,
    "order": 202,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rebel-articles",
    "title": "ENCRYPTED",
    "faction": "rebel",
    "floors": [
      3,
      3
    ],
    "price": 100,
    "order": 203,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rebel-roster",
    "title": "ENCRYPTED",
    "faction": "rebel",
    "floors": [
      4,
      4
    ],
    "price": 100,
    "order": 204,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rebel-interrogation",
    "title": "ENCRYPTED",
    "faction": "rebel",
    "floors": [
      5,
      5
    ],
    "price": 100,
    "order": 205,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rebel-last-call",
    "title": "ENCRYPTED",
    "faction": "rebel",
    "floors": [
      6,
      6
    ],
    "price": 100,
    "order": 206,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "swarm-culture-first",
    "title": "ENCRYPTED",
    "faction": "swarm",
    "floors": [
      1,
      1
    ],
    "price": 100,
    "order": 301,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "swarm-culture-seventh",
    "title": "ENCRYPTED",
    "faction": "swarm",
    "floors": [
      2,
      2
    ],
    "price": 100,
    "order": 302,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "swarm-fragment",
    "title": "ENCRYPTED",
    "faction": "swarm",
    "floors": [
      3,
      3
    ],
    "price": 100,
    "order": 303,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "swarm-breach",
    "title": "ENCRYPTED",
    "faction": "swarm",
    "floors": [
      4,
      4
    ],
    "price": 100,
    "order": 304,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "swarm-sample-b7",
    "title": "ENCRYPTED",
    "faction": "swarm",
    "floors": [
      5,
      5
    ],
    "price": 100,
    "order": 305,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "swarm-notes",
    "title": "ENCRYPTED",
    "faction": "swarm",
    "floors": [
      6,
      6
    ],
    "price": 100,
    "order": 306,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "infiltrator-roster",
    "title": "ENCRYPTED",
    "faction": "any",
    "floors": [
      3,
      3
    ],
    "price": 100,
    "order": 350,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rift-catalogue",
    "title": "ENCRYPTED",
    "faction": "any",
    "floors": [
      5,
      5
    ],
    "price": 100,
    "order": 401,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rift-inscription",
    "title": "ENCRYPTED",
    "faction": "any",
    "floors": [
      6,
      6
    ],
    "price": 100,
    "order": 402,
    "body": "TO BE DECRYPTED"
  },
  {
    "id": "rift-last-inscription",
    "title": "ENCRYPTED",
    "faction": "any",
    "floors": [
      6,
      6
    ],
    "price": 100,
    "order": 403,
    "body": "TO BE DECRYPTED"
  }
];
