// Chinese language table (3.166.0, docs/TEXT_INVENTORY.md). Whole sentences with named slots; see src/i18n.js for
// the slot syntax. Ids are grouped by the module that says them; common.* is shared.
// Generated order is by module, then by first use. Edit the text freely; keep every {slot} a sentence uses.
export default Object.freeze({
 // 共用：好幾個模組說同一句話
 "common.landingRange":"落點需在視線內 {range} 格以內",
 "common.noItem":"沒有{item}",
 "common.ally":"友軍",
 "common.gear":"裝備",
 "common.pickup":"拾取{item}。",
 "common.pickupAmount":"拾取{item} +{n}。",
 "common.magShort":"彈匣不足 {n} 發，請裝填。",
 "common.sentence":"{text}。",
 // 方位
 "dir.none":"",
 "dir.e":"東",
 "dir.w":"西",
 "dir.s":"南",
 "dir.n":"北",
 "dir.es":"東南",
 "dir.en":"東北",
 "dir.ws":"西南",
 "dir.wn":"西北",
 // src/allies.js
 "allies.noRoom":"{ally}無落腳空格，留在原層。",
 "allies.miss":"{ally}射擊／攻擊落空。",
 "allies.reload":"{ally}自動換彈 +{n}。",
 "allies.swapped":"{ally}與{other}交換位置。",
 "allies.noSwap":"{ally}不會和你換位，請繞行。",
 "allies.swapDisabled":"{ally}失能中，無法換位。",
 "allies.swapBlocked":"{ally}無法站到你的位置。",
 "allies.swappedYou":"{ally}與你交換位置，放棄一次行動。",
 // src/blind-fire.js
 "blind-fire.weaponCannot":"{weapon}不能盲射",
 "blind-fire.outOfRange":"超出射程",
 "blind-fire.magShort":"彈匣不足，請裝填",
 "blind-fire.spent":"盲射：消耗 {n} 發。",
 "blind-fire.spentUnseen":"盲射：消耗 {n} 發，看不到結果。",
 // src/callout-ui.js
 "callout-ui.empty":"{item}沒了",
 "callout-ui.itemFallback":"道具",
 // src/civilians.js
 "civilians.scream":"{enemy}尖叫，附近的守衛警戒了。",
 // src/controller.js
 "controller.useItemPaid":"使用{item}，消耗 1 回合",
 "controller.useItemFree":"使用{item}，不耗回合",
 "controller.perkTaken":"已取得 {n} 次",
 "controller.perkTakenPreview":"已取得 {n} 次，選取後 {next} 次",
 "controller.perkRank":"{n}/{cap}",
 "controller.perkRankPreview":"{n}/{cap}，選取後 {next}/{cap}",
 // src/deploy-ui.js
 "deploy-ui.affixFrom":"詞條自第 {floor} 層",
 "deploy-ui.affixFromPreview":"詞條自第 {floor} 層 · 第 2 層起出現特殊敵人",
 "deploy-ui.testFaction":"{name}（測試）",
 // src/endless.js
 "endless.capSupply":"獲得封頂補給（{supply}；超量彈藥留在腳下）。",
 // src/endless-ui.js
 "endless-ui.intro":"沒有任務目標與撤離，每層電梯都通往更深處，直到陣亡。",
 "endless-ui.rules":"{intro}樓層每六層循環：第 3、9、15… 層與第 6、12、18… 層都有頭目擋住電梯。第 7 層起敵人的生命與攻擊逐層按比例成長，每六層每房多一名敵人（最多 +{density}），破壞者、狙擊手、自爆體更多，敵人最高有 {affixCap}% 開始抽取詞條，後續詞條機率逐次減半，效果發動後顯現。死亡時記錄到達深度，全體與各職業各一筆；放棄不列入。",
 "endless-ui.levelCap":"等級 {max} 封頂：2～{max} 級各一次三選一，整局最多 {picks} 次。之後等級不再上升，畫面顯示 MAX；經驗照樣累積，每滿 {every} 點自動發一份封頂補給（{supply}），不開選單、不花回合，超量彈藥留在腳下。一般任務通常到不了 {max} 級。",
 "endless-ui.bestRecord":"第 {floor} 層 · LV.{level} · {kills} 擊殺",
 "endless-ui.growth":"敵人生命 ×{hp}、攻擊 ×{attack}",
 // src/enemy-affixes.js
 "enemy-affixes.name":"{base}{affixes}{cut}{unknown}",
 "enemy-affixes.fragment":"・{fragment}",
 "enemy-affixes.cut":"…",
 "enemy-affixes.unknown":"？",
 // src/enemy-behavior.js
 "enemy-behavior.droneCall":"{enemy}呼叫了無人機增援！",
 "enemy-behavior.attackSource":"{enemy}攻擊",
 "enemy-behavior.miss":"{enemy}未命中（{chance}%）。",
 "enemy-behavior.missReal":"{enemy}未命中。",
 "enemy-behavior.grenadeThrown":"{enemy}已投出榴彈！",
 "enemy-behavior.grenadeReady":"{enemy}準備投彈！",
 // src/enemy-visuals.js
 "enemy-visuals.floorTrait":"（第 {floor} 層起：{trait}）",
 // src/field-gear.js
 "field-gear.decoyFooled":"誘餌啟動：{n} 名敵人被引開，看不到你。",
 "field-gear.decoyHit":"{enemy}攻擊誘餌（{damage}）。",
 "field-gear.decoyHitReal":"{enemy}攻擊誘餌。",
 "field-gear.decoyMiss":"{enemy}沒打中誘餌。",
 "field-gear.mineCap":"同一層最多 {n} 顆地雷",
 "field-gear.mineRange":"埋設點需在視線內 {range} 格以內",
 "field-gear.mineSeen":"地雷埋好了，但有 {n} 名敵人看見，會繞開它。",
 "field-gear.mineShot":"{enemy}開槍引爆了地雷！",
 "field-gear.mineShotMiss":"{enemy}朝地雷開槍，沒打中。",
 // 規則訊息（src/game.js）
 "game.sideTaken":"那一側已經有{barrier}",
 "game.allyCarry":"帶{near} 留{left}",
 "game.containerEmpty":"{container}已開啟，裡面是空的。",
 "game.containerUnderfoot":"{container}已開啟，補給留在腳下，移開再走回拾取。",
 "game.containerSpilled":"{container}已開啟，補給落在地上，走上去拾取。",
 "game.doorLabel":"{side}側{action}",
 "game.doorLocked":"鐵門上鎖",
 "game.doorKeycard":"刷鑰匙卡",
 "game.doorClose":"關門",
 "game.doorOpen":"開門",
 "game.barrierOpened":"{barrier}已開啟。",
 "game.barrierClosed":"{barrier}已關閉。",
 "game.itemOverflow":"{item}超出攜帶上限，{n} 留在腳下。",
 "game.ammoOverflow":"{ammo}超出容量，{n} 留在腳下。",
 "game.grenadeOverflow":"{grenade}超出共用容量，{n} 留在腳下。",
 "game.switchWeaponFree":"切換至{weapon}，不耗回合。",
 "game.meleeChoice":"撞擊時使用{weapon}。",
 "game.warningContacts":"預警取得 {n} 個位置。",
 "game.skillOn":"{skill}啟動：持續 {turns} 回合，冷卻 {cooldown} 回合。",
 "game.gearSwap":"脫下{off}，換上{on}。",
 "game.gearOn":"戴上{gear}。",
 "game.gearOff":"脫下{gear}。",
 "game.switchWeapon":"切換至{weapon}。",
 "game.surge":"腎上腺素：生命 −{hp}，可免費移動 {steps} 格。",
 "game.reloaded":"裝填完成，補充 {n} 發。",
 "game.reloadedFree":"裝填完成，補充 {n} 發，不耗回合。",
 "game.launcherHits":"榴彈落地爆炸，波及 {n} 名敵人。",
 "game.pelletsHit":"{hit}/{count} 顆彈丸打中{target}。",
 "game.pelletsMissed":"彈丸全數落空（{count} 顆）。",
 "game.pelletsHitReal":"彈丸打中{target}。",
 "game.lostLine":"原目標已失去有效射線，向最後確認位置開火落空，消耗 {n} 發。",
 "game.beamMiss":"光束沒打中第 {index} 個：{target}（命中率 {chance}%）。",
 "game.beamHits":"貫穿光束打中直線上 {n} 名敵人。",
 "game.beamHitsAllies":"貫穿光束打中直線上 {n} 名敵人、{allies} 名友軍。",
 "game.recovery":"{weapon}咬進目標：你會跳過下一次行動。",
 "game.shadowReady":"影步就緒：可免費移動 {n} 格。",
 "game.thrustWhiff":"{weapon}刺空了。",
 "game.thrustWhiffReal":"{weapon}刺空。",
 "game.thrustMiss":"{weapon}刺擊未命中（{chance}%）。",
 "game.thrustMissReal":"{weapon}刺擊未命中。",
 "game.freeStepsLeft":"尚可免費移動 {n} 格。",
 "game.stepped.acid":"{target}踩到污染液，受到 {damage} 傷害。",
 "game.stepped.acidReal":"{target}踩到污染液。",
 "game.stepped.heat":"{target}踩到高熱地板，受到 {damage} 傷害。",
 "game.stepped.heatReal":"{target}踩到高熱地板。",
 "game.hit":"命中{target}，造成 {damage} 傷害。",
 "game.hitReal":"命中{target}。",
 "game.killed":"{target}已消滅。",
 "game.lootDropped":"戰利品：{weapon}留在屍體旁，靠近後可拾取。",
 "game.rig":"{container}裝了引信——爆炸！",
 "game.rigLost":"{container}裝了引信——爆炸！裡面的補給全毀。",
 "game.linePull":"{item}把你拉了過去。",
 "game.throw":"投擲{grenade}。",
 "game.disabledYou":"你失能：跳過 {n} 次行動。",
 "game.disabled":"{name}失能：跳過 {n} 次行動。",
 "game.disabledYouReal":"你陷入失能。",
 "game.disabledReal":"{name}陷入失能。",
 "game.allyHurt":"{ally}受傷 −{damage}。",
 "game.allyHurtReal":"{ally}受傷。",
 "game.allyDestroyed":"{ally}已被摧毀。",
 "game.acidHurt":"污染液傷害 −{damage}。",
 "game.heatHurt":"高熱地板傷害 −{damage}。",
 "game.acidHurtReal":"污染液造成傷害。",
 "game.heatHurtReal":"高熱地板造成傷害。",
 "game.ammoFull":"{ammo}容量已滿，剩餘 {n} 留在原地。",
 "game.itemFull":"{item}已達攜帶上限，剩餘 {n} 留在原地。",
 "game.weaponsFull":"武器欄已滿（{n} 格）。可比較並交換武器。",
 "game.weaponSwap":"換入{weapon}；{old}連同彈匣與改裝留在腳下。",
 "game.salvage":"拆解{weapon}，回收彈匣與廢料。",
 "game.salvageFloor":"就地拆解{weapon}，回收彈匣與 {scrap} 廢料。",
 "game.returnFloor":"返回{floor}：物資與戰場保持原狀，沒有換層補給。",
 "game.enterFloor":"進入{floor}。生命 +{hp}，補充各類備彈。",
 "game.objectiveRecovered":"機密資料已回收；{summary}。",
 "game.civilianDown":"{target}已倒下。",
 "game.extracted":"{summary}。撤離成功。",
 "game.launchEmpty":"彈匣已空，請裝填",
 "game.healNotNeeded":"生命已滿且未中毒",
 "game.platesFull":"護甲板已滿",
 "game.surgeFatal":"生命不足以承受",
 "game.protocolEarned":"協定點數 +{n}，死亡仍保留。",
 "game.sprayUsed":"使用修復噴劑，護甲板 +{n}。",
 "game.meleeMiss":"近戰揮擊未命中（{chance}%）。",
 "game.playerHurt":"{source}{notes}，生命 −{damage}。",
 "game.playerHurtReal":"{source}{notes}，你受傷了。",
 "game.noteCover":"（掩體減傷）",
 "game.noteExo":"（外骨骼吸收 {n}）",
 "game.notePlates":"（護甲板吸收 {n}）",
 "game.noteArmor":"（護甲吸收）",
 "game.blastSource":"爆炸衝擊",
 "game.platesRepaired":"修復護甲板 +{n}（{plates}/{cap}）。",
 "game.scrapGained":"回收廢料 +{n}。",
 "game.storyDecrypted":"資料已解密：{body}",
 "game.weaponCollected":"取得武器：{weapon}。在背包中裝備。",
 "game.perkInstalled":"模組已安裝：{perk}。",
 // src/killhouse-ui.js
 "killhouse-ui.best":"最高分 {score}（{character}）",
 "killhouse-ui.score":"最高分 {score}",
 "killhouse-ui.disposedTutorial":"模擬中陣亡。此庫存判定不合格，已銷毀；訓練紀錄不保存。",
 "killhouse-ui.disposedArcade":"模擬中陣亡。此庫存判定不合格，已銷毀；本次成績不列入紀錄。",
 "killhouse-ui.arcadeIntro":"街機模式：整備後進入單層訓練場，沒有升級、掉落與頭目，只記最高分。",
 // src/learning.js
 "learning.dismantled":"拆解{item}，廢料 +{scrap}。",
 "learning.learned":"已學會{item}。",
 // src/learning-data.js
 "learning-data.item":"{name}學習資料",
 // manual
 "manual.intro":"部署時選擇要六層深入、三層往返或無盡深入。點上方任務標題查詢進度。",
 "manual.classesTitle":"職業",
 "manual.classes":"每個職業的數值與起始裝備寫在部署畫面；本局的被動與強化在右上選單的「幹員狀態」。",
 "manual.class.soldier":"自己有掩體時命中提高，連續射擊同一個敵人越打越準。技能「預警」掃描附近的敵人並標定它們，標定中你對它們更準、傷害更高。",
 "manual.class.recon":"橫向移動時較難被打中；手槍彈種的武器免費裝填（仍扣備彈）。技能「訊號斷層」讓敵人暫時無法更新你的位置，但會去搜索最後看到你的地方。",
 "manual.class.engineer":"見〈{allies}〉。",
 "manual.class.bulwark":"大型、緩速，生命與裝甲高，直接傷害再減免；難以治療，回血減半。朝相鄰敵人移動會用選定的近戰武器攻擊（預設動力拳），手上的槍不換。技能「下錨」：啟動與解除各 1 回合，下錨時不能移動，自己的射擊與近戰每回合出手兩次、各自消耗彈藥。",
 "manual.class.berserker":"綁定狂戰斧。鉤鎖把 {range} 格內鎖定的敵人拉到身邊，大型與頭目改由你衝過去，到位後砍一刀；地圖會預覽落點。近戰傷害會回血，近戰擊殺累積戰意減傷；每多帶一把近戰武器，攻擊與減傷都提高。",
 "manual.class.ninja":"綁定忍刀，開局帶齊煙霧、震撼、誘餌、地雷與兩種繩索。光學迷彩降低敵人對你的命中，但不會讓敵人看不到你。目標失能或還沒發現你、你或目標站在煙霧中，或你站在暗處時，近戰傷害 ×{ambush}（伏擊）。只有一名已發現你的敵人看得到你時，迴避提高（單挑）。",
 "manual.alliesTitle":"友軍",
 "manual.allies":"工程師的工坊技能，在技能打開工坊頁面並在空的生產序列花廢料生產機體（1 回合）；完成的機體點身邊 2 步內的空格部署（1 回合）。部署後即不得回收，但可以在旁邊打開工坊修理。製造時可以將背包裡的遠程武器裝上機體，並使用你身上的彈藥換彈，被打爆時武器掉在原地。擊毀特定敵人可以取得它們的藍圖。朝非定點砲台的機體移動會換位。換層時，{carry} 格可通路內的友軍同行。",
 "manual.doorsTitle":"門與隔板",
 "manual.doors":"障礙物在兩格之間，不占地板。朝關門移動：花 1 回合開門，人留原地；再移動才通過。正面或斜角可從右下互動鍵開／關，皆花 1 回合、人留原地；斜角與同側門前格之間不能有牆或障礙阻隔。點門板或隔板邊界可鎖定破壞：門耐久 60、隔板 90。關閉時阻擋通行、視線與爆炸，並提供方向性掩體；打開或摧毀後讓出通道。人型／一般機械會開門，獸類與重型近戰敵人破門。敵人記得最後看見你的位置，關門不會讓它忘記你。矮隔板耐久 60、不擋視線或爆炸，提供箱體等級的掩護；朝它移動會直接翻過去（1 回合），翻過之後到你下次行動前，被射擊命中 +20，敵我相同；落點有人時不能翻。",
 "manual.orderTitle":"行動順序",
 "manual.order":"快速 → 普通 → 緩速，同速玩家先行動。選定有效行動後不能重選；射擊追蹤原目標，目標先移出視線／射程仍向最後確認位置開火落空，消耗彈藥與回合。移動閃避維持到自己的下次行動；狙擊手的蓄勢鎖定仍射向原落點。回合末才結算轟炸與地形。等待（F／句點／中央鈕）：到你下次行動前，直接傷害減半、被射擊命中 −15；下次射擊命中 +15（最高 99%）。任何有效行動後失效。",
 "manual.grenadeTitle":"手榴彈",
 "manual.grenade":"先在背包的投擲物分頁預備，按 G 或投擲物按鈕，點地板選落點，再按右下「確認投擲」；再按一次投擲物按鈕取消。四種投擲物共用容量，效果寫在各自的說明裡。破片會炸到自己；震撼彈也會影響自己，失能時按中央等待恢復。",
 "manual.bagTitle":"背包",
 "manual.bag":"按背包鈕打開背包，會回到上次的分頁；武器鈕直接打開武器分頁，長按投擲物、道具或技能鈕則打開對應的分頁。預備投擲物、道具與技能不耗回合，使用才耗。在背包直接點武器換裝，按鈕上寫著要幾回合；交換、拾取、拆解、改裝與補給各 1 回合，比較不耗時。最多帶 {packLimit} 把武器，走上武器時有空格就收下。幹員數值、本局強化與被動規則在右上選單的「幹員狀態」。",
 "manual.supplyTitle":"補給",
 "manual.supply":"低矮補給箱可以走過、不提供掩體。靠近後按右下互動開箱（1 回合），內容落在地上，走上去拾取。每層有彈藥庫、醫療室與裝甲庫，地圖上可以查看已發現的補給。彈藥、投擲物與道具各有攜帶上限，多出的留在地上。護甲板吸收直接傷害的至多一半，不擋毒液與高熱。終端一次交易一項、1 回合：付廢料，或拿身上的東西抵價；每台有 {credit} 額度，只賣自己那一類（軍械彈藥、治療、道具）。逃命繩索與重部署鉤索從背包或道具鍵使用，點 {lineRange} 格內看得見的地板，沿直線把你拉過去。拆解武器回收備彈與廢料；改裝最多 +3。",
 "manual.pursuitTitle":"雜兵與追擊",
 "manual.pursuit":"雜兵與巢穴幼蟲不給經驗或掉落。由你擊殺敵人後，可以免費再攻擊一次。",
 // src/melee-classes.js
 "melee-classes.grappleTarget":"鉤鎖需要先鎖定 {range} 格內、看得到的敵人。",
 "melee-classes.grappleFixed":"固定中無法衝向目標。",
 "melee-classes.grappleLanding":"沒有可到達的近戰落點：身邊或目標旁都被擋住。",
 // src/melee-ui.js
 "melee-ui.spiritFade":"戰意 {stacks}（{turns} 回合後 −1）",
 "melee-ui.blades":"刃藏 {n} 把 · 攻擊 +{attack}% · 受傷 −{defense}%",
 "melee-ui.spirit":"戰意 {n} 層 · 受傷 −{defense}%",
 // src/missions.js
 "missions.exit.down":"下樓",
 "missions.exit.up":"上樓",
 "missions.exit.extract":"撤離",
 "missions.exit.enter":"進入訓練場",
 "missions.summaryReturnExit":"{mission} · 回程 {floor} → 1 · 前往入口撤離",
 "missions.summaryReturnUp":"{mission} · 回程 {floor} → 1 · 返回本層入口上樓",
 "missions.summaryDepth":"{mission} · 目標位於第 {depth} 層",
 "missions.summaryProgress":"{mission} · {done}/{total} · {goal}",
 "missions.goalExit":"前往撤離電梯",
 "missions.goalRecover":"尋找青色資料匣",
 "missions.goalHunt":"殲滅標記目標",
 "missions.goalBoss":"擊敗頭目",
 "missions.objectivesLeft":"任務目標 {done}/{total}，完成後才能撤離。",
 "missions.summaryEndless":"{mission} · 第 {floor} / {total} 層",
 // src/perks.js
 "perks.repeatable":"已取得 {n} 次 · 可重複",
 // src/poison.js
 "poison.hurt":"中毒傷害 −{damage}。",
 // src/pounce.js
 "pounce.landed":"{enemy}撲到你面前！",
 "pounce.missed":"{enemy}撲空，露出破綻。",
 "pounce.crouch":"{enemy}伏低身子準備撲擊：離開這一格！",
 // src/rebels.js
 "rebels.executed":"{enemy}處決了{victim}。",
 "rebels.alarm":"{enemy}發出警告，附近的敵人全部警戒了。",
 "rebels.spotted":"{enemy}盯上了躲著的{victim}！",
 "rebels.rallyFire":"叛軍歸隊，{n} 人立刻開火！",
 "rebels.morale":"叛軍士氣高漲：{n} 人獲得一回合增益。",
 // src/retreat.js
 "retreat.wave":"撤退增援：本層 {n} 個傳送訊號，兩次行動後抵達；不再追加。",
 // settings
 "settings.music":"選單、探索與交戰各有配樂；十回合看不到敵人後切回探索。",
 "settings.grit":"音效隨機帶一點音高偏移、爆音與靜電，配樂加上錄影帶抖音。",
 "settings.opacity":"0% 完全透明，100% 不透明。",
 "settings.retarget":"鎖定的敵人不在射程內時，改鎖定射程內打得到、離你最近的敵人。",
 "settings.fps":"畫面每秒更新的次數。降低畫面更新頻率可以節省裝置的耗電。",
 "settings.brightness":"畫面的亮度。",
 "settings.vhs":"VHS 風格濾鏡，顯示掃描線、雜訊、暗角與緩慢捲動的訊號帶效果。",
 "settings.shake":"開槍、爆炸與中彈時晃動畫面。",
 "settings.glitch":"畫面上會出現的紅青錯開、橫向撕裂的雜訊。",
 "settings.motion":"系統設定「減少動態效果」時，畫面震動與訊號干擾預設關閉，VHS 的雜訊與訊號帶不會動。",
 "settings.layout":"九宮格把裝填與互動移到方向鍵兩側；格狀把整個操作區排成同尺寸的方格，沒有方向鍵大小可調。",
 "settings.hotkeys":"在按鈕左上角標出鍵盤按鍵。",
 // src/skills.js
 "skills.warningEvasion":"、它們對你的命中 −{n}",
 "skills.earlyWarning":"免費掃描 {radius} 格內敵人，穿牆顯示當下位置光點，維持至下一次耗回合行動結束，並標定它們 {markTurns} 回合：標定中你對它們命中 +{accuracy}、傷害 +{damage}%{evasion}。不追蹤移動、不提供射線，也不會讓敵人發現你。冷卻 {cooldown} 次耗回合行動。",
 "skills.signalBreak":"免費啟動，{turns} 次耗回合行動內敵人無法更新你的位置；仍會搜索最後目擊處。冷卻從啟動起算 {cooldown} 次耗回合行動。已鎖定的狙擊與轟炸仍會落下，下樓結束效果但不重置冷卻。",
 "skills.camouflage":"免費啟動。接下來 {turns} 次付費行動內，敵人對你的射擊與近戰命中 −{evasion}，攻擊不會解除。效果結束後才開始冷卻 {cooldown} 回合，伏擊可縮短。迷彩不會讓敵人看不到你。",
 "skills.workshop":"打開生產序列，不耗回合。空的序列花廢料生產機體（1 回合）；完成的機體點身邊 2 步內空格部署（1 回合），部署後不回收；受損的機體站在旁邊從工坊修理（{repairCost} 廢料、1 回合、回復一半生命）。追隨無人機 {droneHp} HP、{droneMag} 發、射程 {droneRange}，跟在你身邊、可以換位；定點砲台裝甲 {sentryArmor}、可用掩體、{sentryMag} 發、不移動。生產時可把背包裡的遠程武器裝上機體，改用那把武器射擊與換彈，被打爆時武器掉落。機體在你 {carry} 步內自己用你身上的彈藥換彈（內建輕機槍用手槍彈），繩索 {tether} 格。浮游彈藥花廢料與 1 顆投擲物生產、生命 {munitionHp}、不算部署上限，接近敵人後俯衝並在同一次行動引爆；你在爆炸範圍內也會被波及。擊毀巡弋無人機或自爆機器人會取得藍圖（每種一次）：改造無人機生命 {droneUnitHp}、電漿槍射程 {droneUnitRange}、吃能量電池，會追擊繩索內的敵人；改造自爆機器人生命 {bomberHp}、不算部署上限，蓄勢一次後自爆，被打爆時也會爆炸。擊毀封鎖官或核心守衛取得頭目藍圖（只吃廢料、每局製作一次）：改造封鎖官生命 {wardenHp}、每次射擊前蓄力；改造核心守衛生命 {bossHp}、槍擊與延遲轟炸交替，轟炸範圍內的你也會受傷。基礎 {lines} 條序列、同時部署 {deploy} 台，職業升級各可加到 4。",
 "skills.grapple":"鉤住目前鎖定、{range} 格內看得到的敵人（可斜向）：一般敵人拉到你身邊，大型與頭目改由你衝過去，到位後用斧頭砍一刀。花 1 回合，冷卻 {cooldown}（含施放回合）。沒有落點時不能使用、不花回合。",
 // src/squad.js
 "squad.calledShot":"{enemy}依小隊長回報的位置朝你開火。",
 "squad.suppressYou":"{enemy}朝你壓制射擊。",
 "squad.suppressNear":"{enemy}朝你身邊壓制射擊。",
 "squad.identified":"{enemy}識別了你的{weapon}，小隊開始展開。",
 "squad.weaponFallback":"武器",
 "squad.ready":"{enemy}下令：小隊已就緒。",
 "squad.reported":"{enemy}回報你的位置。",
 "squad.search":"{enemy}下令：交叉掩護，搜索最後位置。",
 "squad.disband":"{enemy}的小隊找不到你，解散搜索。",
 "squad.lostTarget":"{enemy}：失去目標，原地待命。",
 // src/status-timers.js
 "status-timers.trait":"{name} {turns} 回合",
 "status-timers.cloud":"{name} {turns} 回合",
 "status-timers.freeSteps":"免費移動 {n} 步",
 "status-timers.poison":"中毒 {stacks} 層 · {turns} 回合",
 "status-timers.disabled":"失能 {n} 回合 · 按等待",
 "status-timers.immune":"失能免疫 {n} 回合",
 "status-timers.signalBreak":"斷層 {n} 回合",
 "status-timers.camouflage":"迷彩 {n} 回合",
 // src/suppression-ui.js
 "suppression-ui.status":"壓制 {stacks} · 命中 −{penalty} · {turns} 回合",
 "suppression-ui.statusPinned":"壓制 {stacks} · 命中 −{penalty} · 無法移動 · {turns} 回合",
 "suppression-ui.tag":"壓制 {stacks}/{max} · 命中 −{penalty}",
 "suppression-ui.tagPinned":"壓制 {stacks}/{max} · 命中 −{penalty} · 釘住",
 "suppression-ui.detailPassive":"被動 · 學會後直接生效{rank}。{detail}",
 "suppression-ui.detailSkill":"主動技能 · 學會後到技能分頁預備{rank}。{detail}",
 "suppression-ui.traitRank":"（{n}/3 階）",
 "suppression-ui.traitTurns":"（剩 {n} 回合）",
 "suppression-ui.skillLine":"{name}：{text}",
 "suppression-ui.rank":" · 目前 {rank}/{max} 階",
 "suppression-ui.traitLine":"{name}{rank}{turns}：{text}",
 "suppression-ui.help":"壓制最多 {max} 層，每層射擊與近戰命中 −{accuracy}；{pinned} 層以上不能移動（仍可攻擊、裝填、使用道具），每個單位自己行動完後層數減半、無條件進位，1 層則歸零（敵我相同；5 層依序是 5、3、2、1）。一次攻擊打出至少 {weaponRounds} 發並命中，目標得 1 層；壓制射擊消耗 {skillRounds} 發、每發命中 −{skillAccuracy}，範圍內敵人保底 1 層，命中者再加 1 層。頭目少 1 層，機械不受壓制。壓制抗性每階使單次壓制合計 −1 層，最高 3 階，可用學習資料提升；部分職業、重裝兵與頭目天生 1 階。未識別貨櫃可能掉出武器或學習資料：在背包道具分頁使用或拆解（+{scrap} 廢料），都不耗回合；學會的主動技能與職業技能共用一格預備欄。",
 // src/suppressive-fire.js
 "suppressive-fire.magMin":"彈匣至少需要 {n} 發。",
 "suppressive-fire.fired":"壓制射擊，消耗 {n} 發。",
 // src/swarm-fields.js
 "swarm-fields.lobbed":"{enemy}拋出毒霧。",
 "swarm-fields.swelling":"{enemy}鼓起毒囊，準備拋出毒霧！",
 // src/target-card.js
 "target-card.pelletsBase":"（原 {min}–{max}）",
 "target-card.band":" · 有效 {band}",
 "target-card.single":" · 單發",
 "target-card.double":" · 兩發",
 "target-card.pellets":"{count} 顆 × {low}–{high}{base} · 每顆 {chance}%",
 "target-card.magShort":"彈匣不足 {n} 發",
 "target-card.hit":"命中 {chance}%",
 "target-card.distance":"距離 {range} 格\n射程 {weaponRange} 格{band}{burst}",
 // src/terminal.js
 "terminal.deal":"終端交易：{got}。付出 {paid}。此終端剩餘額度 {left}。",
 "terminal.dealSpent":"終端交易：{got}。付出 {paid}。此終端剩餘額度 {left}，已耗盡。",
 "terminal.notSold":"{terminal}不賣這一類。",
 "terminal.creditShort":"此終端剩餘額度 {left}，不夠 {price}。",
 "terminal.rounds":"{n} 發",
 "terminal.roundsShort":"不足 {n} 發",
 "terminal.rowReason":"{item}：{reason}。",
 "terminal.rowShort":"{item}不夠。",
 "terminal.upgraded":"{weapon}改裝 +{n}，單次傷害 +5",
 // src/throwables.js
 "throwables.emp":"射程 5、半徑 2。機械中斷蓄勢並跳過 {turns} 次行動（通常含投擲當回合），頭目 {bossTurns} 次；恢復後免疫 {immunity} 次行動。不扣生命。",
 "throwables.stun":"射程 5、半徑 2。生物或有夜視／紅外線者中斷蓄勢並跳過 {turns} 次行動（通常含投擲當回合），頭目 {bossTurns} 次；恢復後免疫 {immunity} 次行動。會震暈自己，同樣 {turns} 次。",
 // src/weapons.js
 "weapons.extendedBurst":" · 延伸點射：{range} 格內兩發，{from}–{to} 格單發",
 // src/workshop.js
 "workshop.queuedPayload":"與 1 顆{grenade}",
 "workshop.queuedWeapon":"（{weapon}）",
 "workshop.deployedPayload":"（{grenade}）",
 "workshop.blueprintMissing":"尚未取得藍圖：擊毀{enemy}後取得。",
 "workshop.scrapShort":"廢料不足，需要 {n}。",
 "workshop.noPayload":"沒有{item}。",
 "workshop.queued":"消耗 {cost} 廢料{payload}，{unit}{weapon}已放進生產序列。",
 "workshop.deployCap":"部署上限 {n} 台已滿。",
 "workshop.allyCapLost":"友軍名額已滿：留在第 {floor} 層的{ally}已失去連線。",
 "workshop.weaponDropped":"{weapon}掉在{ally}的位置。",
 "workshop.deployed":"{ally}{payload}已部署。",
 "workshop.undamaged":"{ally}沒有損傷。",
 "workshop.repaired":"消耗 {cost} 廢料修理{ally}，生命 +{n}（{hp}/{max}）。",
 "workshop.munitionDive":"浮游彈藥俯衝引爆{grenade}。",
 "workshop.blueprint":"取得藍圖：{unit}。打開工坊就能生產。",
});
