// Chinese language table (3.166.0, docs/TEXT_INVENTORY.md). Whole sentences with named slots; see src/i18n.js for
// the slot syntax. Ids are grouped by the module that says them; common.* is shared.
// Generated order is by module, then by first use. Edit the text freely; keep every {slot} a sentence uses.
export default Object.freeze({
 // 共用：好幾個模組說同一句話
 "common.landingRange":"落點需在視線內 {range} 格以內",
 "common.noItem":"沒有{item}",
 "common.ally":"友軍",
 "common.gear":"裝備",
 "common.pickup":"拾取{item}。",
 "common.pickupAmount":"拾取{item} +{n}。",
 "common.magShort":"彈匣不足 {n} 發，請裝填。",
 "common.sentence":"{text}。",
 // 方位
 "dir.none":"",
 "dir.e":"東",
 "dir.w":"西",
 "dir.s":"南",
 "dir.n":"北",
 "dir.es":"東南",
 "dir.en":"東北",
 "dir.ws":"西南",
 "dir.wn":"西北",
 // abandonCopy
 "abandonCopy.title":"任務已放棄。",
 "abandonCopy.body":"已賺取的協定點數與解鎖保留，這次任務已結束。",
 // affixes
 "affixes.stable.name":"穩定",
 "affixes.stable.text":"命中 +10；基礎傷害 −10%",
 "affixes.piercing.name":"穿甲",
 "affixes.piercing.text":"穿透 +25%；彈匣 −25%（向下取整，至少 1 發）",
 "affixes.extended.name":"擴容",
 "affixes.extended.text":"彈匣 +50%（向下取整）；命中 −8",
 "affixes.powerful.name":"強擊",
 "affixes.powerful.text":"基礎傷害 +15%；彈匣 −25%（向下取整，至少 1 發）",
 "affixes.longbarrel.name":"長管",
 "affixes.longbarrel.text":"射程 +2；基礎傷害 −10%",
 "affixes.shortbarrel.name":"短管",
 "affixes.shortbarrel.text":"射程 −2、有效距離前後各 −2；切換到這把不耗回合；基礎傷害 −10%",
 "affixes.tracking.name":"追獵",
 "affixes.tracking.text":"目標移動的命中懲罰減為 10；基礎傷害 −10%",
 "affixes.lance.name":"貫穿",
 "affixes.lance.text":"光束穿過目標繼續前進，打中直線上每個看得見的單位（各自判定命中），在射程盡頭或碰到牆、門、掩體、油桶才停；每次射擊耗 2 發；基礎傷害 −15%",
 "affixes.burst.name":"爆裂",
 "affixes.burst.text":"命中後在目標處爆炸，相鄰一格受到命中傷害的一半（會波及自己與友軍、引爆油桶）；每次射擊耗 2 發；基礎傷害 −15%",
 "affixes.rapid.name":"速射",
 "affixes.rapid.text":"一次射擊只耗 1 發，連射 3 發，每發 18–22、穿透 50%；命中會造成壓制（機械免疫）",
 // src/allies.js
 "allies.noRoom":"{ally}無落腳空格，留在原層。",
 "allies.miss":"{ally}射擊／攻擊落空。",
 "allies.reload":"{ally}自動換彈 +{n}。",
 "allies.swapped":"{ally}與{other}交換位置。",
 "allies.noSwap":"{ally}不會和你換位，請繞行。",
 "allies.swapDisabled":"{ally}失能中，無法換位。",
 "allies.swapBlocked":"{ally}無法站到你的位置。",
 "allies.swappedYou":"{ally}與你交換位置，放棄一次行動。",
 // src/ammunition.js
 "ammunition.pistol.name":"手槍彈",
 "ammunition.pistol.short":"手槍彈",
 "ammunition.rifle.name":"步槍彈",
 "ammunition.rifle.short":"步槍彈",
 "ammunition.shell.name":"霰彈",
 "ammunition.shell.short":"霰彈",
 "ammunition.energy.name":"能量電池",
 "ammunition.energy.short":"電池",
 "ammunition.ordnance.name":"發射器榴彈",
 "ammunition.ordnance.short":"榴彈",
 "ammunition.grenade.name":"手榴彈",
 "ammunition.grenade.short":"手榴彈",
 // barrierTypes
 "barrierTypes.door.name":"隔離門",
 "barrierTypes.low_partition.name":"矮隔板",
 "barrierTypes.partition.name":"隔板",
 // src/blind-fire.js
 "blind-fire.weaponCannot":"{weapon}不能盲射",
 "blind-fire.outOfRange":"超出射程",
 "blind-fire.magShort":"彈匣不足，請裝填",
 "blind-fire.spent":"盲射：消耗 {n} 發。",
 "blind-fire.spentUnseen":"盲射：消耗 {n} 發，看不到結果。",
 // src/callout-ui.js
 "callout-ui.empty":"{item}沒了",
 "callout-ui.itemFallback":"道具",
 // src/characters.js
 "characters.engineer.label":"工程師",
 "characters.engineer.text":"用工坊生產追隨無人機與定點砲台，選一台部署；機體靠近你時用你的手槍彈換彈，部署後不回收。拆解武器的廢料 +50%。",
 "characters.soldier.label":"士兵",
 "characters.soldier.text":"天生射擊命中 +8，利用掩體穩定壓制同一目標；預警會標定掃到的敵人，標定中對它們命中與傷害更高；開局帶十點護甲板。",
 "characters.bulwark.label":"重裝兵",
 "characters.bulwark.text":"厚重動力裝甲承受火力，以輕機槍壓制、動力拳破陣。普通敵人先行動；可下錨固定位置，在普通與緩速各攻擊一次。",
 "characters.recon.label":"偵察兵",
 "characters.recon.text":"天生射擊迴避 +10、投擲容量 +2，煙霧／震撼各兩顆；每次升級配給一顆煙霧；夜視與紅外線支援側身作戰；衝鋒槍可在原射程外 2 格單發點射。",
 "characters.berserker.label":"狂戰士",
 "characters.berserker.text":"血厚的近戰職業。鉤鎖把敵人拉到身邊，大型與頭目則衝過去，到位後補一刀；近戰吸血，連續斬殺疊減傷，攜帶的近戰武器越多越強。射擊較不準。天生壓制抗性一階、抗毒一階。",
 "characters.ninja.label":"忍者",
 "characters.ninja.text":"偵察兵的近戰變體。光學迷彩讓敵人難以命中；目標失能、任一方在煙霧中、目標還沒發現他或他身在暗處時伏擊加傷，只剩一名敵人看得到他時更難被打中。副武器是衝鋒槍，3 格內射擊忽略掩體與目標移動、命中 +10；投擲容量 +2，開局四顆煙霧彈與一顆震撼彈，誘餌、地雷、逃命繩索與重部署鉤索各五個。",
 // src/civilians.js
 "civilians.scream":"{enemy}尖叫，附近的守衛警戒了。",
 // containerKinds
 "containerKinds.unknown.name":"未識別貨櫃",
 "containerKinds.ammo.name":"彈藥箱",
 "containerKinds.medical.name":"醫療箱",
 "containerKinds.armor.name":"護甲箱",
 "containerKinds.ordnance.name":"投擲物箱",
 "containerKinds.salvage.name":"廢料箱",
 "containerKinds.supply.name":"補給箱",
 "containerKinds.field.name":"器材箱",
 "containerKinds.vault.name":"保險箱",
 "containerKinds.fallback":"補給箱",
 // src/controller.js
 "controller.useItemPaid":"使用{item}，消耗 1 回合",
 "controller.useItemFree":"使用{item}，不耗回合",
 "controller.perkTaken":"已取得 {n} 次",
 "controller.perkTakenPreview":"已取得 {n} 次，選取後 {next} 次",
 "controller.perkRank":"{n}/{cap}",
 "controller.perkRankPreview":"{n}/{cap}，選取後 {next}/{cap}",
 // deckLabels
 "deckLabels.up":"向上",
 "deckLabels.down":"向下",
 "deckLabels.left":"向左",
 "deckLabels.right":"向右",
 "deckLabels.wait":"等待",
 "deckLabels.fire":"開火",
 "deckLabels.reload":"裝填",
 "deckLabels.grenade":"手榴彈",
 "deckLabels.item":"道具",
 "deckLabels.skill":"技能",
 "deckLabels.interact":"互動",
 // src/deploy-ui.js
 "deploy-ui.affixFrom":"詞條自第 {floor} 層",
 "deploy-ui.affixFromPreview":"詞條自第 {floor} 層 · 第 2 層起出現特殊敵人",
 "deploy-ui.testFaction":"{name}（測試）",
 // src/endless.js
 "endless.capSupply":"獲得封頂補給（{supply}；超量彈藥留在腳下）。",
 // src/endless-ui.js
 "endless-ui.intro":"沒有任務目標與撤離，每層電梯都通往更深處，直到陣亡。",
 "endless-ui.rules":"{intro}樓層每六層循環：第 3、9、15… 層與第 6、12、18… 層都有頭目擋住電梯。第 7 層起敵人的生命與攻擊逐層按比例成長，每六層每房多一名敵人（最多 +{density}），破壞者、狙擊手、自爆體更多，敵人最高有 {affixCap}% 開始抽取詞條，後續詞條機率逐次減半，效果發動後顯現。死亡時記錄到達深度，全體與各職業各一筆；放棄不列入。",
 "endless-ui.levelCap":"等級 {max} 封頂：2～{max} 級各一次三選一，整局最多 {picks} 次。之後等級不再上升，畫面顯示 MAX；經驗照樣累積，每滿 {every} 點自動發一份封頂補給（{supply}），不開選單、不花回合，超量彈藥留在腳下。一般任務通常到不了 {max} 級。",
 "endless-ui.bestRecord":"第 {floor} 層 · LV.{level} · {kills} 擊殺",
 "endless-ui.growth":"敵人生命 ×{hp}、攻擊 ×{attack}",
 // src/enemy-affixes.js
 "enemy-affixes.name":"{base}{affixes}{cut}{unknown}",
 "enemy-affixes.fragment":"・{fragment}",
 "enemy-affixes.cut":"…",
 "enemy-affixes.unknown":"？",
 // src/enemy-behavior.js
 "enemy-behavior.droneCall":"{enemy}呼叫了無人機增援！",
 "enemy-behavior.attackSource":"{enemy}攻擊",
 "enemy-behavior.miss":"{enemy}未命中（{chance}%）。",
 "enemy-behavior.missReal":"{enemy}未命中。",
 "enemy-behavior.grenadeThrown":"{enemy}已投出榴彈！",
 "enemy-behavior.grenadeReady":"{enemy}準備投彈！",
 // src/enemy-visuals.js
 "enemy-visuals.floorTrait":"（第 {floor} 層起：{trait}）",
 // enemyAffixes
 "enemyAffixes.fast.fragment":"快速",
 "enemyAffixes.infrared.fragment":"紅外線",
 "enemyAffixes.night_vision.fragment":"夜視",
 "enemyAffixes.suppressor.fragment":"壓制者",
 "enemyAffixes.grenadier.fragment":"擲彈兵",
 "enemyAffixes.venomous.fragment":"帶毒",
 "enemyAffixes.brood_host.fragment":"育蟲",
 "enemyAffixes.deployer.fragment":"投放",
 // 敵人：名稱與介紹（src/data.js）
 "enemyTypes.fodder.name":"失能遊蕩者",
 "enemyTypes.fodder.role":"緩速、每兩次行動機會活動一次。徒手可清理，擊殺獲得追擊。",
 "enemyTypes.brood.name":"裂隙幼蟲",
 "enemyTypes.brood.role":"巢穴釋出的快速幼蟲。沒有戰利品，擊殺獲得追擊。",
 "enemyTypes.rifleman.name":"斷訊槍兵",
 "enemyTypes.rifleman.role":"低耐久、自動步槍連續壓制。先找牆角或掩體，再優先擊殺。",
 "enemyTypes.raider.name":"破口突擊兵",
 "enemyTypes.raider.role":"近距離高傷害、低生命。與槍兵交叉火力，勿停在暴露通道。",
 "enemyTypes.crawler.name":"裂隙獵犬",
 "enemyTypes.crawler.role":"接近後蓄勢撕咬。拉開一格即可避開攻擊。",
 "enemyTypes.gunner.name":"叛變哨兵",
 "enemyTypes.gunner.role":"中距離槍擊。牆壁阻擋射線，掩體可減傷。",
 "enemyTypes.drone.name":"無人機",
 "enemyTypes.drone.role":"可飛越地形傷害與掩體，但無法穿牆。",
 "enemyTypes.brute.name":"破壞者",
 "enemyTypes.brute.role":"重裝近戰。用狙擊、電漿或爆炸穿透護甲。",
 "enemyTypes.sniper.name":"盲眼狙擊手",
 "enemyTypes.sniper.role":"具夜視，忽略暗區懲罰；射程 10 格，瞄準需要兩回合。",
 "enemyTypes.bomber.name":"孢子自爆體",
 "enemyTypes.bomber.role":"死亡或近身蓄勢後爆炸。保持至少 2 格距離。",
 "enemyTypes.warden.name":"封鎖官",
 "enemyTypes.warden.role":"具紅外線可穿煙，但也怕震撼彈。攻擊需蓄勢，掉落稀有軍械。",
 "enemyTypes.boss.name":"核心守衛",
 "enemyTypes.boss.role":"反應核心頭目。交替槍擊與延遲轟炸，離開紅色標記。",
 "enemyTypes.bomber_bot.name":"自爆機器人",
 "enemyTypes.bomber_bot.role":"近身蓄勢後自爆，被擊毀時也會爆炸。機械：怕 EMP、不受壓制。保持至少 2 格距離。",
 "enemyTypes.giant_bug.name":"巨型蟲",
 "enemyTypes.giant_bug.role":"血很多、沒有裝甲的巨蟲。穿甲沒有用，要靠持續火力。",
 "enemyTypes.hive_beast.name":"巢穴巨獸",
 "enemyTypes.hive_beast.role":"第 3 層的蟲族頭目：生命極高、沒有裝甲的近戰巨獸。",
 "enemyTypes.hive_matriarch.name":"母巢巨獸",
 "enemyTypes.hive_matriarch.role":"第 6 層的蟲族頭目：比巢穴巨獸更大、更耐打。",
 "enemyTypes.rifleman_infected.name":"被感染槍兵",
 "enemyTypes.raider_infected.name":"被感染突擊兵",
 "enemyTypes.infected.role":"被蟲族寄生的士兵：一次連發很多發，但幾乎打不準；只要命中仍會造成壓制。",
 "enemyTypes.squad_leader.name":"小隊長",
 "enemyTypes.squad_leader.role":"指揮官：識別你手上的武器，把隊員派到能有效還擊的位置，並讓全隊保持「已就緒」。它活著時隊員會壓制你。",
 "enemyTypes.enforcer.name":"督戰官",
 "enemyTypes.enforcer.role":"叛軍的督戰官：行動緩慢，一把射程很遠卻幾乎打不中的槍。看到你會警告附近所有敵人，然後躲到掩體後，不會自己衝上來。盯上躲起來的叛軍、下一回合處決，讓周圍所有人立刻歸隊開火。先殺它，或搶先殺掉被盯上的那個。",
 "enemyTypes.munition.name":"浮游彈藥",
 "enemyTypes.munition.role":"出現後下一回合以鉤索移到你身邊引爆。退出射程或直接打下來。",
 "enemyTypes.civilian.name":"滯留研究員",
 "enemyTypes.civilian.role":"不戰鬥的設施人員。看到你會尖叫並一直逃跑。",
 "enemyTypes.spitter.name":"毒液噴吐蟲",
 "enemyTypes.spitter.role":"噴吐毒液，命中不直接傷害，延長中毒時間。",
 // src/factions.js
 "factions.conscript":"強徵兵",
 "factions.unknownUnit":"未知單位",
 "factions.legacy.name":"現行混合",
 "factions.loyalist.name":"忠誠者",
 "factions.rebel.name":"叛軍",
 "factions.swarm.name":"蟲族",
 "factions.swarm.overrides.fodder.name":"被感染者",
 "factions.swarm.overrides.brood.name":"蟲群幼體",
 "factions.swarm.overrides.crawler.name":"獵殺蟲",
 // src/field-gear.js
 "field-gear.decoyFooled":"誘餌啟動：{n} 名敵人被引開，看不到你。",
 "field-gear.decoyHit":"{enemy}攻擊誘餌（{damage}）。",
 "field-gear.decoyHitReal":"{enemy}攻擊誘餌。",
 "field-gear.decoyMiss":"{enemy}沒打中誘餌。",
 "field-gear.mineCap":"同一層最多 {n} 顆地雷",
 "field-gear.mineRange":"埋設點需在視線內 {range} 格以內",
 "field-gear.mineSeen":"地雷埋好了，但有 {n} 名敵人看見，會繞開它。",
 "field-gear.mineShot":"{enemy}開槍引爆了地雷！",
 "field-gear.mineShotMiss":"{enemy}朝地雷開槍，沒打中。",
 // 樓層提示（src/data.js）
 "floorInfo.0.text":"轉運站。殘存補給未清點。",
 "floorInfo.1.text":"冷卻區遭污染，綠色格會造成傷害。",
 "floorInfo.2.text":"電梯由頭目鎖定。軍械箱內存有新式武器。",
 "floorInfo.3.text":"自爆單位會引爆周遭油桶。地面有綠色毒液。",
 "floorInfo.4.text":"熔爐地板高溫。重裝單位與狙擊手據守長廊。",
 "floorInfo.5.text":"頭目擊殺後方可撤離。留意預告標記。",
 // 樓層名稱（src/data.js）
 "floors.0":"軌道轉運站",
 "floors.1":"污染冷卻區",
 "floors.2":"軍械封鎖區",
 "floors.3":"生化培養艙",
 "floors.4":"高壓熔爐",
 "floors.5":"深淵反應核心",
 // furniture
 "furniture.toilet.name":"衛浴設備",
 "furniture.sink.name":"洗手台",
 "furniture.counter.name":"門禁櫃檯",
 "furniture.scanner.name":"檢查設備",
 "furniture.locker.name":"置物櫃",
 "furniture.bench.name":"值勤桌",
 // 規則訊息（src/game.js）
 "game.sideTaken":"那一側已經有{barrier}",
 "game.allyCarry":"帶{near} 留{left}",
 "game.containerEmpty":"{container}已開啟，裡面是空的。",
 "game.containerUnderfoot":"{container}已開啟，補給留在腳下，移開再走回拾取。",
 "game.containerSpilled":"{container}已開啟，補給落在地上，走上去拾取。",
 "game.doorLabel":"{side}側{action}",
 "game.doorLocked":"鐵門上鎖",
 "game.doorKeycard":"刷鑰匙卡",
 "game.doorClose":"關門",
 "game.doorOpen":"開門",
 "game.barrierOpened":"{barrier}已開啟。",
 "game.barrierClosed":"{barrier}已關閉。",
 "game.itemOverflow":"{item}超出攜帶上限，{n} 留在腳下。",
 "game.ammoOverflow":"{ammo}超出容量，{n} 留在腳下。",
 "game.grenadeOverflow":"{grenade}超出共用容量，{n} 留在腳下。",
 "game.switchWeaponFree":"切換至{weapon}，不耗回合。",
 "game.meleeChoice":"撞擊時使用{weapon}。",
 "game.warningContacts":"預警取得 {n} 個位置。",
 "game.skillOn":"{skill}啟動：持續 {turns} 回合，冷卻 {cooldown} 回合。",
 "game.gearSwap":"脫下{off}，換上{on}。",
 "game.gearOn":"戴上{gear}。",
 "game.gearOff":"脫下{gear}。",
 "game.switchWeapon":"切換至{weapon}。",
 "game.surge":"腎上腺素：生命 −{hp}，可免費移動 {steps} 格。",
 "game.reloaded":"裝填完成，補充 {n} 發。",
 "game.reloadedFree":"裝填完成，補充 {n} 發，不耗回合。",
 "game.launcherHits":"榴彈落地爆炸，波及 {n} 名敵人。",
 "game.pelletsHit":"{hit}/{count} 顆彈丸打中{target}。",
 "game.pelletsMissed":"彈丸全數落空（{count} 顆）。",
 "game.pelletsHitReal":"彈丸打中{target}。",
 "game.lostLine":"原目標已失去有效射線，向最後確認位置開火落空，消耗 {n} 發。",
 "game.beamMiss":"光束沒打中第 {index} 個：{target}（命中率 {chance}%）。",
 "game.beamHits":"貫穿光束打中直線上 {n} 名敵人。",
 "game.beamHitsAllies":"貫穿光束打中直線上 {n} 名敵人、{allies} 名友軍。",
 "game.recovery":"{weapon}咬進目標：你會跳過下一次行動。",
 "game.shadowReady":"影步就緒：可免費移動 {n} 格。",
 "game.thrustWhiff":"{weapon}刺空了。",
 "game.thrustWhiffReal":"{weapon}刺空。",
 "game.thrustMiss":"{weapon}刺擊未命中（{chance}%）。",
 "game.thrustMissReal":"{weapon}刺擊未命中。",
 "game.freeStepsLeft":"尚可免費移動 {n} 格。",
 "game.stepped.acid":"{target}踩到污染液，受到 {damage} 傷害。",
 "game.stepped.acidReal":"{target}踩到污染液。",
 "game.stepped.heat":"{target}踩到高熱地板，受到 {damage} 傷害。",
 "game.stepped.heatReal":"{target}踩到高熱地板。",
 "game.hit":"命中{target}，造成 {damage} 傷害。",
 "game.hitReal":"命中{target}。",
 "game.killed":"{target}已消滅。",
 "game.lootDropped":"戰利品：{weapon}留在屍體旁，靠近後可拾取。",
 "game.rig":"{container}裝了引信——爆炸！",
 "game.rigLost":"{container}裝了引信——爆炸！裡面的補給全毀。",
 "game.linePull":"{item}把你拉了過去。",
 "game.throw":"投擲{grenade}。",
 "game.disabledYou":"你失能：跳過 {n} 次行動。",
 "game.disabled":"{name}失能：跳過 {n} 次行動。",
 "game.disabledYouReal":"你陷入失能。",
 "game.disabledReal":"{name}陷入失能。",
 "game.allyHurt":"{ally}受傷 −{damage}。",
 "game.allyHurtReal":"{ally}受傷。",
 "game.allyDestroyed":"{ally}已被摧毀。",
 "game.acidHurt":"污染液傷害 −{damage}。",
 "game.heatHurt":"高熱地板傷害 −{damage}。",
 "game.acidHurtReal":"污染液造成傷害。",
 "game.heatHurtReal":"高熱地板造成傷害。",
 "game.ammoFull":"{ammo}容量已滿，剩餘 {n} 留在原地。",
 "game.itemFull":"{item}已達攜帶上限，剩餘 {n} 留在原地。",
 "game.weaponsFull":"武器欄已滿（{n} 格）。可比較並交換武器。",
 "game.weaponSwap":"換入{weapon}；{old}連同彈匣與改裝留在腳下。",
 "game.salvage":"拆解{weapon}，回收彈匣與廢料。",
 "game.salvageFloor":"就地拆解{weapon}，回收彈匣與 {scrap} 廢料。",
 "game.returnFloor":"返回{floor}：物資與戰場保持原狀，沒有換層補給。",
 "game.enterFloor":"進入{floor}。生命 +{hp}，補充各類備彈。",
 "game.objectiveRecovered":"機密資料已回收；{summary}。",
 "game.civilianDown":"{target}已倒下。",
 "game.extracted":"{summary}。撤離成功。",
 "game.launchEmpty":"彈匣已空，請裝填",
 "game.healNotNeeded":"生命已滿且未中毒",
 "game.platesFull":"護甲板已滿",
 "game.surgeFatal":"生命不足以承受",
 "game.protocolEarned":"協定點數 +{n}，死亡仍保留。",
 "game.sprayUsed":"使用修復噴劑，護甲板 +{n}。",
 "game.meleeMiss":"近戰揮擊未命中（{chance}%）。",
 "game.playerHurt":"{source}{notes}，生命 −{damage}。",
 "game.playerHurtReal":"{source}{notes}，你受傷了。",
 "game.noteCover":"（掩體減傷）",
 "game.noteExo":"（外骨骼吸收 {n}）",
 "game.notePlates":"（護甲板吸收 {n}）",
 "game.noteArmor":"（護甲吸收）",
 "game.blastSource":"爆炸衝擊",
 "game.platesRepaired":"修復護甲板 +{n}（{plates}/{cap}）。",
 "game.scrapGained":"回收廢料 +{n}。",
 "game.storyDecrypted":"資料已解密：{body}",
 "game.weaponCollected":"取得武器：{weapon}。在背包中裝備。",
 "game.perkInstalled":"模組已安裝：{perk}。",
 // grenades
 "grenades.frag.name":"破片手榴彈",
 "grenades.frag.short":"破片彈",
 "grenades.frag.text":"射程 5、半徑 2。造成爆炸傷害，會自傷及引爆油桶。",
 "grenades.smoke.name":"煙霧彈",
 "grenades.smoke.short":"煙霧彈",
 "grenades.emp.name":"EMP 彈",
 "grenades.stun.name":"震撼彈",
 "grenades.stun.short":"震撼彈",
 "grenades.smoke.text":"射程 5、半徑 2，持續 {turns} 輪（含投擲當輪）。阻斷無紅外線者的視線，煙內僅見相鄰格；紅外線可穿煙，不減傷。",
 // hotkeyActions
 "hotkeyActions.moveUp.group":"移動",
 "hotkeyActions.moveUp.label":"向上移動",
 "hotkeyActions.moveLeft.group":"移動",
 "hotkeyActions.moveLeft.label":"向左移動",
 "hotkeyActions.moveDown.group":"移動",
 "hotkeyActions.moveDown.label":"向下移動",
 "hotkeyActions.moveRight.group":"移動",
 "hotkeyActions.moveRight.label":"向右移動",
 "hotkeyActions.wait.group":"移動",
 "hotkeyActions.wait.label":"等待",
 "hotkeyActions.fire.group":"行動",
 "hotkeyActions.fire.label":"開火",
 "hotkeyActions.reload.group":"行動",
 "hotkeyActions.reload.label":"裝填",
 "hotkeyActions.grenade.group":"行動",
 "hotkeyActions.grenade.label":"投擲",
 "hotkeyActions.item.group":"行動",
 "hotkeyActions.item.label":"道具",
 "hotkeyActions.skill.group":"行動",
 "hotkeyActions.skill.label":"技能",
 "hotkeyActions.interact.group":"行動",
 "hotkeyActions.interact.label":"互動",
 "hotkeyActions.cycleTarget.group":"目標與畫面",
 "hotkeyActions.cycleTarget.label":"切換目標",
 "hotkeyActions.toggleTargeting.group":"目標與畫面",
 "hotkeyActions.toggleTargeting.label":"瞄準資訊開關",
 "hotkeyActions.bag.group":"目標與畫面",
 "hotkeyActions.bag.label":"背包",
 "hotkeyActions.weapons.group":"目標與畫面",
 "hotkeyActions.weapons.label":"武器分頁",
 "hotkeyActions.map.group":"目標與畫面",
 "hotkeyActions.map.label":"樓層地圖",
 "hotkeyActions.center.group":"目標與畫面",
 "hotkeyActions.center.label":"鏡頭復位",
 "hotkeyActions.zoomIn.group":"目標與畫面",
 "hotkeyActions.zoomIn.label":"放大",
 "hotkeyActions.zoomOut.group":"目標與畫面",
 "hotkeyActions.zoomOut.label":"縮小",
 // src/killhouse-ui.js
 "killhouse-ui.best":"最高分 {score}（{character}）",
 "killhouse-ui.score":"最高分 {score}",
 "killhouse-ui.disposedTutorial":"模擬中陣亡。此庫存判定不合格，已銷毀；訓練紀錄不保存。",
 "killhouse-ui.disposedArcade":"模擬中陣亡。此庫存判定不合格，已銷毀；本次成績不列入紀錄。",
 "killhouse-ui.arcadeIntro":"街機模式：整備後進入單層訓練場，沒有升級、掉落與頭目，只記最高分。",
 // labels
 "labels.rangedAccuracy":"射擊命中",
 "labels.rangedEvasion":"射擊迴避",
 "labels.meleeAccuracy":"近戰命中",
 "labels.meleeEvasion":"近戰迴避",
 // largeModuleTypes
 "largeModuleTypes.office.name":"辦公隔間",
 "largeModuleTypes.warehouse.name":"堆棧倉庫",
 "largeModuleTypes.garage.name":"裝甲車庫",
 "largeModuleTypes.hangar.name":"小型機庫",
 // src/learning.js
 "learning.dismantled":"拆解{item}，廢料 +{scrap}。",
 "learning.learned":"已學會{item}。",
 // src/learning-data.js
 "learning-data.item":"{name}學習資料",
 // loyalistNames
 "loyalistNames.squad_leader.name":"小隊長",
 "loyalistNames.rifleman.name":"步槍兵",
 "loyalistNames.rifleman_armored.name":"步槍兵",
 "loyalistNames.raider.name":"突擊兵",
 "loyalistNames.raider_armored.name":"突擊兵",
 "loyalistNames.gunner.name":"破門手",
 "loyalistNames.sniper.name":"狙擊手",
 "loyalistNames.crawler.name":"軍犬",
 // 操作指南（src/controller.js）
 "manual.intro":"部署時選擇要六層深入、三層往返或無盡深入。點上方任務標題查詢進度。",
 "manual.classesTitle":"職業",
 "manual.classes":"每個職業的數值與起始裝備寫在部署畫面；本局的被動與強化在右上選單的「幹員狀態」。",
 "manual.class.soldier":"自己有掩體時命中提高，連續射擊同一個敵人越打越準。技能「預警」掃描附近的敵人並標定它們，標定中你對它們更準、傷害更高。",
 "manual.class.recon":"橫向移動時較難被打中；手槍彈種的武器免費裝填（仍扣備彈）。技能「訊號斷層」讓敵人暫時無法更新你的位置，但會去搜索最後看到你的地方。",
 "manual.class.engineer":"見〈{allies}〉。",
 "manual.class.bulwark":"大型、緩速，生命與裝甲高，直接傷害再減免；難以治療，回血減半。朝相鄰敵人移動會用選定的近戰武器攻擊（預設動力拳），手上的槍不換。技能「下錨」：啟動與解除各 1 回合，下錨時不能移動，自己的射擊與近戰每回合出手兩次、各自消耗彈藥。",
 "manual.class.berserker":"綁定狂戰斧。鉤鎖把 {range} 格內鎖定的敵人拉到身邊，大型與頭目改由你衝過去，到位後砍一刀；地圖會預覽落點。近戰傷害會回血，近戰擊殺累積戰意減傷；每多帶一把近戰武器，攻擊與減傷都提高。",
 "manual.class.ninja":"綁定忍刀，開局帶齊煙霧、震撼、誘餌、地雷與兩種繩索。光學迷彩降低敵人對你的命中，但不會讓敵人看不到你。目標失能或還沒發現你、你或目標站在煙霧中，或你站在暗處時，近戰傷害 ×{ambush}（伏擊）。只有一名已發現你的敵人看得到你時，迴避提高（單挑）。",
 "manual.alliesTitle":"友軍",
 "manual.allies":"工程師按技能打開工坊，在空的生產序列花廢料生產機體（1 回合）；完成的機體點身邊 2 步內的空格部署（1 回合）。部署後即不得回收，但可以在旁邊打開工坊修理。製造時可以將背包裡的遠程武器裝上機體，並使用你身上的彈藥換彈，被打爆時武器掉在原地。擊毀特定敵人可以取得它們的藍圖。朝非定點砲台的機體移動會換位。換層時，{carry} 格可通路內的友軍同行。",
 "manual.doorsTitle":"門與隔板",
 "manual.doors":"障礙物在兩格之間，不占地板。朝關門移動：花 1 回合開門，人留原地；再移動才通過。正面或斜角可從右下互動鈕開／關，皆花 1 回合、人留原地；斜角與同側門前格之間不能有牆或障礙阻隔。點門板或隔板邊界可鎖定破壞：門耐久 60、隔板 90。關閉時阻擋通行、視線與爆炸，並提供方向性掩體；打開或摧毀後讓出通道。人型／一般機械會開門，獸類與重型近戰敵人破門。敵人記得最後看見你的位置，關門不會讓它忘記你。矮隔板耐久 60、不擋視線或爆炸，提供箱體等級的掩護；朝它移動會直接翻過去（1 回合），翻過之後到你下次行動前，被射擊命中 +20，敵我相同；落點有人時不能翻。",
 "manual.orderTitle":"行動順序",
 "manual.order":"快速 → 普通 → 緩速，同速玩家先行動。選定有效行動後不能重選；射擊追蹤原目標，目標先移出視線／射程仍向最後確認位置開火落空，消耗彈藥與回合。移動閃避維持到自己的下次行動；狙擊手的蓄勢鎖定仍射向原落點。回合末才結算轟炸與地形。等待（中央鈕）：到你下次行動前，直接傷害減半、被射擊命中 −15；下次射擊命中 +15（最高 99%）。任何有效行動後失效。",
 "manual.grenadeTitle":"手榴彈",
 "manual.grenade":"先在背包的投擲物分頁預備，按投擲物按鈕，點地板選落點，再按右下「確認投擲」；再按一次投擲物按鈕取消。四種投擲物共用容量，效果寫在各自的說明裡。破片會炸到自己；震撼彈也會影響自己，失能時按中央等待恢復。",
 "manual.bagTitle":"背包",
 "manual.bag":"按背包鈕打開背包，會回到上次的分頁；武器鈕直接打開武器分頁，長按投擲物、道具或技能鈕則打開對應的分頁。預備投擲物、道具與技能不耗回合，使用才耗。在背包直接點武器換裝，按鈕上寫著要幾回合；交換、拾取、拆解、改裝與補給各 1 回合，比較不耗時。最多帶 {packLimit} 把武器，走上武器時有空格就收下。幹員數值、本局強化與被動規則在右上選單的「幹員狀態」。",
 "manual.supplyTitle":"補給",
 "manual.supply":"低矮補給箱可以走過、不提供掩體。靠近後按右下互動開箱（1 回合），內容落在地上，走上去拾取。每層有彈藥庫、醫療室與裝甲庫，地圖上可以查看已發現的補給。彈藥、投擲物與道具各有攜帶上限，多出的留在地上。護甲板吸收直接傷害的至多一半，不擋毒液與高熱。終端一次交易一項、1 回合：付廢料，或拿身上的東西抵價；每台有 {credit} 額度，只賣自己那一類（軍械彈藥、治療、道具）。逃命繩索與重部署鉤索從背包或道具鈕使用，點 {lineRange} 格內看得見的地板，沿直線把你拉過去。拆解武器回收備彈與廢料；改裝最多 +3。",
 "manual.pursuitTitle":"雜兵與追擊",
 "manual.pursuit":"雜兵與巢穴幼蟲不給經驗或掉落。由你擊殺敵人後，可以免費再攻擊一次。",
 "manual.directionsTitle":"四方向",
 "manual.directions":"↑ ↓ ← → 就是畫面上的上下左右。用方向鈕或點相鄰格移動。每個按鈕都有對應的鍵盤按鍵，可以在設定的「鍵盤」段更改，也能讓按鈕左上角顯示按鍵。",
 "manual.fireTitle":"射擊",
 "manual.fire":"點敵人、掩體或油桶鎖定，再按開火。目標鈕輪換敵人。目標在射程外時，地圖會用黃框閃兩下標出你現在打得到的範圍；設定可開啟「超出射程時自動改鎖最近的敵人」。瞄準鈕收起或顯示浮卡、鎖定框及目標取景，關閉時仍可開火，視野如同沒有鎖定目標；點擊敵人會重新開啟瞄準。有敵人時會閃爍提醒。",
 "manual.exitTitle":"撤離",
 "manual.exit":"到綠色電梯鄰格，按電梯按鈕。本層頭目或最終任務要求未完成時電梯鎖定。",
 // src/melee-classes.js
 "melee-classes.grappleTarget":"鉤鎖需要先鎖定 {range} 格內、看得到的敵人。",
 "melee-classes.grappleFixed":"固定中無法衝向目標。",
 "melee-classes.grappleLanding":"沒有可到達的近戰落點：身邊或目標旁都被擋住。",
 // src/melee-ui.js
 "melee-ui.spiritFade":"戰意 {stacks}（{turns} 回合後 −1）",
 "melee-ui.blades":"刃藏 {n} 把 · 攻擊 +{attack}% · 受傷 −{defense}%",
 "melee-ui.spirit":"戰意 {n} 層 · 受傷 −{defense}%",
 // src/missions.js
 "missions.exit.down":"下樓",
 "missions.exit.up":"上樓",
 "missions.exit.extract":"撤離",
 "missions.exit.enter":"進入訓練場",
 "missions.summaryReturnExit":"{mission} · 回程 {floor} → 1 · 前往入口撤離",
 "missions.summaryReturnUp":"{mission} · 回程 {floor} → 1 · 返回本層入口上樓",
 "missions.summaryDepth":"{mission} · 目標位於第 {depth} 層",
 "missions.summaryProgress":"{mission} · {done}/{total} · {goal}",
 "missions.goalExit":"前往撤離電梯",
 "missions.goalRecover":"尋找青色資料匣",
 "missions.goalHunt":"殲滅標記目標",
 "missions.goalBoss":"擊敗頭目",
 "missions.objectivesLeft":"任務目標 {done}/{total}，完成後才能撤離。",
 "missions.summaryEndless":"{mission} · 第 {floor} / {total} 層",
 "missions.extraction.name":"核心撤離",
 "missions.extraction.text":"深入六層，擊敗第 3 層與第 6 層的頭目，再從電梯撤離。",
 "missions.hunt.name":"定點清除",
 "missions.hunt.text":"第 6 層殲滅 1 名指定敵人，再從電梯撤離；第 6 層頭目不是必要目標。",
 "missions.sweep.name":"獵殺名單",
 "missions.sweep.text":"第 6 層殲滅分布在不同房間的 3 名指定敵人，再從電梯撤離。",
 "missions.retrieval.name":"機密回收",
 "missions.retrieval.text":"第 6 層找到 1 份機密資料，靠近後互動回收，再從電梯撤離。",
 "missions.roundtrip.name":"原路回收",
 "missions.roundtrip.text":"深入三層，回收機密並擊敗第 3 層頭目，沿原路返回第 1 層入口撤離。回程各層一次傳送增援，不補發物資、回血或彈藥。",
 "missions.archive.name":"分散檔案",
 "missions.archive.text":"第 6 層從不同房間回收 3 份機密資料，再從電梯撤離。",
 "missions.endless.name":"無盡深入",
 "missions.endless.text":"沒有撤離：每層電梯都通往更深處，直到陣亡。第 7 層起敵人更多、更強，還可能帶精英特性；等級 {max} 封頂後，升級改發補給。",
 // moduleTypes
 "moduleTypes.restroom.name":"衛浴間",
 "moduleTypes.checkpoint.name":"門禁櫃檯",
 "moduleTypes.guardpost.name":"值勤哨站",
 // nestStyles
 "nestStyles.burrow.name":"蟲群地洞",
 "nestStyles.rift.name":"裂隙傳送門",
 // operatorColors
 "operatorColors.amber.label":"琥珀",
 "operatorColors.red.label":"赤紅",
 "operatorColors.blue.label":"鈷藍",
 "operatorColors.cyan.label":"青碧",
 "operatorColors.green.label":"軍綠",
 "operatorColors.violet.label":"紫羅蘭",
 "operatorColors.white.label":"雪白",
 "operatorColors.none.label":"原色",
 // 升級：名稱與說明（src/data.js）
 "perks.repeatable":"已取得 {n} 次 · 可重複",
 "perks.damage.name":"武器增幅",
 "perks.damage.text":"每次完整武器攻擊傷害合計 +4，連發分攤；每次近戰 +4。",
 "perks.damage.classic.text":"每次完整武器攻擊傷害合計 +6，連發分攤；每次近戰 +6。",
 "perks.health.name":"生存本能",
 "perks.health.text":"最大生命 +20，立即回復 30 生命。",
 "perks.health.classic.text":"最大生命 +25，立即回復 40 生命。",
 "perks.armor.name":"複合裝甲",
 "perks.armor.text":"每次直接受傷減少 2 點。",
 "perks.armor.classic.text":"每次直接受傷減少 3 點。",
 "perks.med.name":"戰地補給",
 "perks.med.text":"獲得 2 醫療包、2 手榴彈與分類備彈；超量彈藥留在腳下。",
 "perks.blast.name":"爆破專家",
 "perks.blast.text":"破片手榴彈與爆炸武器傷害 +12。",
 "perks.blast.classic.text":"破片手榴彈與爆炸武器傷害 +18。",
 "perks.scavenger.name":"資源回收",
 "perks.scavenger.text":"擊殺與撿到的廢料 +50%，立即獲得 15 廢料。",
 "perks.medic.name":"急救訓練",
 "perks.medic.text":"醫療包回復量 +20；立即獲得 1 醫療包。",
 "perks.hazmat.name":"密封防護",
 "perks.hazmat.text":"環境傷害 −5、中毒每回合傷害 −1，立即解除中毒；第 3 階免疫現有環境傷害。",
 "perks.accuracy.name":"精準射擊",
 "perks.accuracy.text":"射擊命中 +5 個百分點。",
 "perks.accuracy.classic.text":"射擊命中 +8 個百分點。",
 "perks.evasion.name":"戰術閃避",
 "perks.evasion.text":"被射擊命中 −5 個百分點。",
 "perks.evasion.classic.text":"被射擊命中 −8 個百分點。",
 "perks.melee.name":"格鬥訓練",
 "perks.melee.text":"近戰命中與近戰迴避各 +8 個百分點。",
 "perks.plating.name":"裝甲回收",
 "perks.plating.text":"有裝甲的敵人掉落護甲板的機率 +15 個百分點（基礎 20%），一般敵人也有 6% 機率掉落 5 點；立即獲得 10 護甲板。",
 "perks.steady.name":"沉著",
 "perks.steady.text":"等待後下一次射擊的命中加成 +8（基礎 15）。",
 "perks.skirmish.name":"游擊",
 "perks.skirmish.text":"你移動之後，敵人射擊你時的移動懲罰 +6（基礎 22）。",
 "perks.mod_mastery.name":"改裝精通",
 "perks.mod_mastery.text":"身上武器的一般詞條，好處放大 25%，壞處不變（射程無條件捨去）；貫穿、爆裂、速射不受影響。身上有帶一般詞條的武器才會出現。",
 "perks.plate_rack.name":"加掛板架",
 "perks.plate_rack.text":"護甲板上限 +10，立即獲得 10 護甲板。",
 "perks.bulwark_plating.name":"板甲護持",
 "perks.bulwark_plating.text":"護甲板還有剩時，直接傷害額外 −8%；每階累加。",
 "perks.bulwark_recovery.name":"板材回收",
 "perks.bulwark_recovery.text":"敵人掉落護甲板機率 +15 個百分點、每份 +5 點；可與裝甲回收疊加。",
 "perks.bulwark_anchor.name":"下錨強化",
 "perks.bulwark_anchor.text":"下錨中受到的直接傷害 −10%；第 3 階解除下錨不耗回合。",
 "perks.berserker_fury.name":"狂怒堆疊",
 "perks.berserker_fury.text":"戰意層數上限 +1。",
 "perks.berserker_endure.name":"血怒不退",
 "perks.berserker_endure.text":"戰意開始衰減的延遲 +2 回合、每層衰減間隔 +1 回合。",
 "perks.berserker_thirst.name":"嗜血狂歡",
 "perks.berserker_thirst.text":"近戰吸血 +8 個百分點（基礎 20%）。",
 "perks.engineer_salvage.name":"戰場回收",
 "perks.engineer_salvage.text":"每次擊殺額外 +2 廢料；立即獲得 15 廢料。",
 "perks.engineer_frame.name":"機體強化",
 "perks.engineer_frame.text":"所有機體最大生命 +20、裝甲 +1。已部署的機體立即增加上限，不直接修復。",
 "perks.engineer_firecontrol.name":"火控校準",
 "perks.engineer_firecontrol.text":"所有機體射擊命中 +8 個百分點、傷害 +3。",
 "perks.engineer_lines.name":"生產序列",
 "perks.engineer_lines.text":"工坊生產序列 +1 條（基礎 1 條）。",
 "perks.engineer_deploy.name":"部署上限",
 "perks.engineer_deploy.text":"同時部署的機體 +1 台（基礎 1 台，留在別層的不算）。",
 "perks.soldier_overwatch.name":"廣域預警",
 "perks.soldier_overwatch.text":"預警半徑 +2、冷卻 −1（最低 2）。",
 "perks.soldier_marked.name":"標定弱化",
 "perks.soldier_marked.text":"預警的標定持續 +1 回合；標定者對你的命中 −6。",
 "perks.soldier_hunter.name":"標定壓制",
 "perks.soldier_hunter.text":"預警的標定持續 +1 回合；你對標定者的傷害 +10%。",
 "perks.recon_unseen.name":"隱蔽射手",
 "perks.recon_unseen.text":"射擊目標看不到你時，每階傷害 +12%。",
 "perks.recon_blackout.name":"斷層延長",
 "perks.recon_blackout.text":"訊號斷層持續 +1、冷卻 −1（最低 3）。",
 "perks.recon_sidestep.name":"側身精通",
 "perks.recon_sidestep.text":"側身使敵人命中每階再 −6，暴露下限同步放寬。",
 "perks.ninja_shadowstep.name":"影步",
 "perks.ninja_shadowstep.text":"伏擊命中後取得免費移動；二階延長至 2 格，三階結束時可追加伏擊。",
 "perks.ninja_ambush.name":"伏擊精通",
 "perks.ninja_ambush.text":"伏擊傷害倍率每階 +0.15。",
 "perks.ninja_overload.name":"光學過載",
 "perks.ninja_overload.text":"迷彩持續 +1、冷卻 −2（最低 4）。",
 "perks.ammo_recovery.name":"彈藥回收",
 "perks.ammo_recovery.text":"一般敵人彈藥掉落率每階 +15 個百分點（35% → 50% → 65% → 80%）。",
 // src/poison.js
 "poison.hurt":"中毒傷害 −{damage}。",
 // src/pounce.js
 "pounce.landed":"{enemy}撲到你面前！",
 "pounce.missed":"{enemy}撲空，露出破綻。",
 "pounce.crouch":"{enemy}伏低身子準備撲擊：離開這一格！",
 // preparedCatalog
 "preparedCatalog.item.medkit.name":"醫療包",
 "preparedCatalog.item.medkit.short":"醫療包",
 "preparedCatalog.item.medkit.text":"回復生命並清除中毒。使用消耗 1 回合，滿血且未中毒時不消耗。",
 "preparedCatalog.item.spray.name":"修復噴劑",
 "preparedCatalog.item.spray.short":"噴劑",
 "preparedCatalog.item.spray.text":"補上 20 點護甲板。使用消耗 1 回合，護甲板已滿時無法使用。",
 "preparedCatalog.item.adrenaline.name":"腎上腺素",
 "preparedCatalog.item.adrenaline.short":"腎上腺素",
 "preparedCatalog.item.adrenaline.text":"不消耗回合。接下來可免費移動 2 格，做其他事就結束；代價是 15 生命。",
 "preparedCatalog.item.barricade.name":"摺疊掩體",
 "preparedCatalog.item.barricade.short":"掩體",
 "preparedCatalog.item.barricade.text":"在身邊任一側的邊線架起矮隔板：擋住移動並提供掩體，但不擋視線與射線，任何人都能翻越（翻越者下次被射擊命中 +20）。使用消耗 1 回合。",
 "preparedCatalog.item.flare.name":"照明彈",
 "preparedCatalog.item.flare.short":"照明彈",
 "preparedCatalog.item.flare.text":"射程 5 格、半徑 3 格，持續 8 輪。落點看得到、而且沒有對照明彈取得完整掩體的暗格會被照亮：站在上面的敵我都失去暗區的命中懲罰。",
 "preparedCatalog.item.escape_line.name":"逃命繩索",
 "preparedCatalog.item.escape_line.short":"逃命繩",
 "preparedCatalog.item.escape_line.text":"不消耗回合。朝 6 格內看得見的地板射出繩索，沿直線把你拉過去；牆、實心物件和其他單位會擋住，幼蟲不會。一條只能用一次。",
 "preparedCatalog.item.redeploy_line.name":"重部署鉤索",
 "preparedCatalog.item.redeploy_line.short":"鉤索",
 "preparedCatalog.item.redeploy_line.text":"消耗 1 回合。朝 6 格內看得見的地板射出鉤索，沿直線把你拉過去；牆、實心物件和其他單位會擋住，幼蟲不會。一條只能用一次。",
 "preparedCatalog.item.irg.name":"紅外線護目鏡",
 "preparedCatalog.item.irg.short":"紅外",
 "preparedCatalog.item.irg.text":"佩戴期間看得穿煙霧（牆與關著的門照樣擋），不抵銷暗區懲罰；會受震撼彈失能。戴上與脫下各消耗 1 回合，佩戴期間道具鍵停用。",
 "preparedCatalog.item.nvg.name":"夜視鏡",
 "preparedCatalog.item.nvg.short":"夜視",
 "preparedCatalog.item.nvg.text":"佩戴期間忽略目標暗區的射擊命中懲罰（不穿煙）。戴上與脫下各消耗 1 回合，佩戴期間道具鍵停用。",
 "preparedCatalog.item.decoy.name":"誘餌",
 "preparedCatalog.item.decoy.short":"誘餌",
 "preparedCatalog.item.decoy.text":"射程 5 格。落點 6 格內的敵人（頭目、自爆單位除外）會把誘餌當成你：看不到你、改去攻擊誘餌，但照樣打你的友軍。你攻擊的敵人、以及看得到牠被攻擊的敵人會回過神來；走到你旁邊的也會看穿。誘餌 30 耐久，維持 4 回合。消耗 1 回合。",
 "preparedCatalog.item.mine.name":"地雷",
 "preparedCatalog.item.mine.short":"地雷",
 "preparedCatalog.item.mine.text":"埋在 3 格內看得見的空地上，同一層最多 3 顆。走路的敵人踩到就爆炸：中心 60、相鄰 50（加上爆破專家）；你和友軍踩到不會爆，但會被炸到。其他爆炸也會引爆它。敵人看不到地雷；看著你埋的會繞開，有槍的會在爆炸範圍外開槍引爆它。換層後就沒了。消耗 1 回合。",
 "preparedCatalog.item.exo.name":"外骨骼",
 "preparedCatalog.item.exo.short":"外骨骼",
 "preparedCatalog.item.exo.text":"射擊命中 +10、近戰傷害 +20%，自帶 50 點護甲板，受傷時先替你吸收（和護甲板一樣吸收一半）。護甲板打光時外骨骼損毀、消失，你直接被壓制 5 層。無法修復；重裝兵穿不下。戴上與脫下各消耗 1 回合。",
 // preparedCategories
 "preparedCategories.grenade":"手榴彈",
 "preparedCategories.item":"道具",
 "preparedCategories.skill":"技能",
 // rebelNames
 "rebelNames.drone.name":"叛變無人機",
 "rebelNames.brute.name":"叛變破壞者",
 "rebelNames.rifleman.name":"叛變步槍兵",
 "rebelNames.raider.name":"叛變突擊兵",
 "rebelNames.raider_elite.name":"叛變突擊兵",
 "rebelNames.gunner.name":"叛變破門手",
 "rebelNames.gunner_elite.name":"叛變破門手",
 "rebelNames.sniper.name":"叛變狙擊手",
 "rebelNames.crawler.name":"叛變軍犬",
 // src/rebels.js
 "rebels.executed":"{enemy}處決了{victim}。",
 "rebels.alarm":"{enemy}發出警告，附近的敵人全部警戒了。",
 "rebels.spotted":"{enemy}盯上了躲著的{victim}！",
 "rebels.rallyFire":"叛軍歸隊，{n} 人立刻開火！",
 "rebels.morale":"叛軍士氣高漲：{n} 人獲得一回合增益。",
 // src/retreat.js
 "retreat.wave":"撤退增援：本層 {n} 個傳送訊號，兩次行動後抵達；不再追加。",
 // sceneryFurniture
 "sceneryFurniture.desk.name":"辦公桌",
 "sceneryFurniture.pallet.name":"貨物堆棧",
 "sceneryFurniture.rover.cockpit":"裝甲車座艙",
 "sceneryFurniture.rover.part":"裝甲車部件",
 "sceneryFurniture.shuttle.cockpit":"穿梭艇座艙",
 "sceneryFurniture.shuttle.part":"穿梭艇部件",
 // 設定頁說明（src/controller.js）
 "settings.music":"選單、探索與交戰各有配樂；十回合看不到敵人後切回探索。",
 "settings.grit":"音效隨機帶一點音高偏移、爆音與靜電，配樂加上錄影帶抖音。",
 "settings.opacity":"0% 完全透明，100% 不透明。",
 "settings.retarget":"鎖定的敵人不在射程內時，改鎖定射程內打得到、離你最近的敵人。",
 "settings.fps":"畫面每秒更新的次數。降低畫面更新頻率可以節省裝置的耗電。",
 "settings.brightness":"畫面的亮度。",
 "settings.vhs":"VHS 風格濾鏡，顯示掃描線、雜訊、暗角與緩慢捲動的訊號帶效果。",
 "settings.shake":"開槍、爆炸與中彈時晃動畫面。",
 "settings.glitch":"畫面上會出現的紅青錯開、橫向撕裂的雜訊。",
 "settings.motion":"系統設定「減少動態效果」時，畫面震動與訊號干擾預設關閉，VHS 的雜訊與訊號帶不會動。",
 "settings.layout":"九宮格把裝填與互動移到方向鍵兩側；格狀把整個操作區排成同尺寸的方格，沒有方向鍵大小可調。",
 "settings.hotkeys":"在按鈕左上角標出鍵盤按鍵。",
 // src/skills.js
 "skills.warningEvasion":"、它們對你的命中 −{n}",
 "skills.earlyWarning":"免費掃描 {radius} 格內敵人，穿牆顯示當下位置光點，維持至下一次耗回合行動結束，並標定它們 {markTurns} 回合：標定中你對它們命中 +{accuracy}、傷害 +{damage}%{evasion}。不追蹤移動、不提供射線，也不會讓敵人發現你。冷卻 {cooldown} 次耗回合行動。",
 "skills.signalBreak":"免費啟動，{turns} 次耗回合行動內敵人無法更新你的位置；仍會搜索最後目擊處。冷卻從啟動起算 {cooldown} 次耗回合行動。已鎖定的狙擊與轟炸仍會落下，下樓結束效果但不重置冷卻。",
 "skills.camouflage":"免費啟動。接下來 {turns} 次付費行動內，敵人對你的射擊與近戰命中 −{evasion}，攻擊不會解除。效果結束後才開始冷卻 {cooldown} 回合，伏擊可縮短。迷彩不會讓敵人看不到你。",
 "skills.workshop":"打開生產序列，不耗回合。空的序列花廢料生產機體（1 回合）；完成的機體點身邊 2 步內空格部署（1 回合），部署後不回收；受損的機體站在旁邊從工坊修理（{repairCost} 廢料、1 回合、回復一半生命）。追隨無人機 {droneHp} HP、{droneMag} 發、射程 {droneRange}，跟在你身邊、可以換位；定點砲台裝甲 {sentryArmor}、可用掩體、{sentryMag} 發、不移動。生產時可把背包裡的遠程武器裝上機體，改用那把武器射擊與換彈，被打爆時武器掉落。機體在你 {carry} 步內自己用你身上的彈藥換彈（內建輕機槍用手槍彈），繩索 {tether} 格。浮游彈藥花廢料與 1 顆投擲物生產、生命 {munitionHp}、不算部署上限，接近敵人後俯衝並在同一次行動引爆；你在爆炸範圍內也會被波及。擊毀巡弋無人機或自爆機器人會取得藍圖（每種一次）：改造無人機生命 {droneUnitHp}、電漿槍射程 {droneUnitRange}、吃能量電池，會追擊繩索內的敵人；改造自爆機器人生命 {bomberHp}、不算部署上限，蓄勢一次後自爆，被打爆時也會爆炸。擊毀封鎖官或核心守衛取得頭目藍圖（只吃廢料、每局製作一次）：改造封鎖官生命 {wardenHp}、每次射擊前蓄力；改造核心守衛生命 {bossHp}、槍擊與延遲轟炸交替，轟炸範圍內的你也會受傷。基礎 {lines} 條序列、同時部署 {deploy} 台，職業升級各可加到 4。",
 "skills.grapple":"鉤住目前鎖定、{range} 格內看得到的敵人（可斜向）：一般敵人拉到你身邊，大型與頭目改由你衝過去，到位後用斧頭砍一刀。花 1 回合，冷卻 {cooldown}（含施放回合）。沒有落點時不能使用、不花回合。",
 "skills.suppressive_fire.name":"壓制射擊",
 "skills.suppressive_fire.short":"壓制",
 "skills.suppressive_fire.text":"消耗 3 發，命中 −20；目標格與相鄰四格敵人獲得 1 層壓制，命中可再加 1 層。",
 "skills.anchor.name":"下錨",
 "skills.anchor.short":"下錨",
 "skills.anchor.text":"啟動／解除各 1 回合。下錨時不能移動或換層，套用笨拙；自己的武器射擊與近戰於普通與緩速各執行一次，分別消耗彈藥；投擲物與友軍不受影響。",
 "skills.workshop.name":"工坊",
 "skills.workshop.short":"工坊",
 "skills.workshop.card":"打開生產序列 · 生產與部署各 1 回合",
 "skills.early_warning.name":"預警",
 "skills.early_warning.short":"預警",
 "skills.signal_break.name":"訊號斷層",
 "skills.signal_break.short":"斷層",
 "skills.grapple.name":"鉤鎖",
 "skills.grapple.short":"鉤鎖",
 "skills.camouflage.name":"光學迷彩",
 "skills.camouflage.short":"迷彩",
 "skills.status.release":"解除",
 "skills.status.activate":"啟動",
 "skills.status.active":"生效 {n}",
 "skills.status.cooldown":"冷卻 {n}",
 "skills.status.ready":"就緒",
 // src/squad.js
 "squad.calledShot":"{enemy}依小隊長回報的位置朝你開火。",
 "squad.suppressYou":"{enemy}朝你壓制射擊。",
 "squad.suppressNear":"{enemy}朝你身邊壓制射擊。",
 "squad.identified":"{enemy}識別了你的{weapon}，小隊開始展開。",
 "squad.weaponFallback":"武器",
 "squad.ready":"{enemy}下令：小隊已就緒。",
 "squad.reported":"{enemy}回報你的位置。",
 "squad.search":"{enemy}下令：交叉掩護，搜索最後位置。",
 "squad.disband":"{enemy}的小隊找不到你，解散搜索。",
 "squad.lostTarget":"{enemy}：失去目標，原地待命。",
 // src/status-timers.js
 "status-timers.trait":"{name} {turns} 回合",
 "status-timers.cloud":"{name} {turns} 回合",
 "status-timers.freeSteps":"免費移動 {n} 步",
 "status-timers.poison":"中毒 {stacks} 層 · {turns} 回合",
 "status-timers.disabled":"失能 {n} 回合 · 按等待",
 "status-timers.immune":"失能免疫 {n} 回合",
 "status-timers.signalBreak":"斷層 {n} 回合",
 "status-timers.camouflage":"迷彩 {n} 回合",
 // 補給與物資名稱（src/data.js）
 "supplyNames.ammo":"步槍彈",
 "supplyNames.pistol":"手槍彈",
 "supplyNames.shell":"霰彈",
 "supplyNames.energy":"能量電池",
 "supplyNames.ordnance":"榴彈彈藥",
 "supplyNames.med":"醫療包",
 "supplyNames.armor":"護甲板",
 "supplyNames.grenade":"破片手榴彈",
 "supplyNames.smoke":"煙霧彈",
 "supplyNames.emp":"EMP 彈",
 "supplyNames.stun":"震撼彈",
 "supplyNames.scrap":"廢料",
 "supplyNames.weapon":"武器箱",
 "supplyNames.lore":"資料片段",
 "supplyNames.spray":"修復噴劑",
 "supplyNames.adrenaline":"腎上腺素",
 "supplyNames.barricade":"摺疊掩體",
 "supplyNames.flare":"照明彈",
 "supplyNames.nvg":"夜視鏡",
 "supplyNames.escape_line":"逃命繩索",
 "supplyNames.redeploy_line":"重部署鉤索",
 "supplyNames.decoy":"誘餌",
 "supplyNames.mine":"地雷",
 "supplyNames.exo":"外骨骼",
 "supplyNames.key":"鑰匙卡",
 "supplyNames.irg":"紅外線護目鏡",
 // src/suppression-ui.js
 "suppression-ui.status":"壓制 {stacks} · 命中 −{penalty} · {turns} 回合",
 "suppression-ui.statusPinned":"壓制 {stacks} · 命中 −{penalty} · 無法移動 · {turns} 回合",
 "suppression-ui.tag":"壓制 {stacks}/{max} · 命中 −{penalty}",
 "suppression-ui.tagPinned":"壓制 {stacks}/{max} · 命中 −{penalty} · 釘住",
 "suppression-ui.detailPassive":"被動 · 學會後直接生效{rank}。{detail}",
 "suppression-ui.detailSkill":"主動技能 · 學會後到技能分頁預備{rank}。{detail}",
 "suppression-ui.traitRank":"（{n}/3 階）",
 "suppression-ui.traitTurns":"（剩 {n} 回合）",
 "suppression-ui.skillLine":"{name}：{text}",
 "suppression-ui.rank":" · 目前 {rank}/{max} 階",
 "suppression-ui.traitLine":"{name}{rank}{turns}：{text}",
 "suppression-ui.help":"壓制最多 {max} 層，每層射擊與近戰命中 −{accuracy}；{pinned} 層以上不能移動（仍可攻擊、裝填、使用道具），每個單位自己行動完後層數減半、無條件進位，1 層則歸零（敵我相同；5 層依序是 5、3、2、1）。一次攻擊打出至少 {weaponRounds} 發並命中，目標得 1 層；壓制射擊消耗 {skillRounds} 發、每發命中 −{skillAccuracy}，範圍內敵人保底 1 層，命中者再加 1 層。頭目少 1 層，機械不受壓制。壓制抗性每階使單次壓制合計 −1 層，最高 3 階，可用學習資料提升；部分職業、重裝兵與頭目天生 1 階。未識別貨櫃可能掉出武器或學習資料：在背包道具分頁使用或拆解（+{scrap} 廢料），都不耗回合；學會的主動技能與職業技能共用一格預備欄。",
 // src/suppressive-fire.js
 "suppressive-fire.magMin":"彈匣至少需要 {n} 發。",
 "suppressive-fire.fired":"壓制射擊，消耗 {n} 發。",
 // src/swarm-fields.js
 "swarm-fields.lobbed":"{enemy}拋出毒霧。",
 "swarm-fields.swelling":"{enemy}鼓起毒囊，準備拋出毒霧！",
 // src/target-card.js
 "target-card.pelletsBase":"（原 {min}–{max}）",
 "target-card.band":" · 有效 {band}",
 "target-card.single":" · 單發",
 "target-card.double":" · 兩發",
 "target-card.pellets":"{count} 顆 × {low}–{high}{base} · 每顆 {chance}%",
 "target-card.magShort":"彈匣不足 {n} 發",
 "target-card.hit":"命中 {chance}%",
 "target-card.distance":"距離 {range} 格\n射程 {weaponRange} 格{band}{burst}",
 // src/terminal.js
 "terminal.deal":"終端交易：{got}。付出 {paid}。此終端剩餘額度 {left}。",
 "terminal.dealSpent":"終端交易：{got}。付出 {paid}。此終端剩餘額度 {left}，已耗盡。",
 "terminal.notSold":"{terminal}不賣這一類。",
 "terminal.creditShort":"此終端剩餘額度 {left}，不夠 {price}。",
 "terminal.rounds":"{n} 發",
 "terminal.roundsShort":"不足 {n} 發",
 "terminal.rowReason":"{item}：{reason}。",
 "terminal.rowShort":"{item}不夠。",
 "terminal.upgraded":"{weapon}改裝 +{n}，單次傷害 +5",
 // terminalKinds
 "terminalKinds.arms":"軍械彈藥終端",
 "terminalKinds.medical":"治療終端",
 "terminalKinds.gear":"道具終端",
 // src/throwables.js
 "throwables.emp":"射程 5、半徑 2。機械中斷蓄勢並跳過 {turns} 次行動（通常含投擲當回合），頭目 {bossTurns} 次；恢復後免疫 {immunity} 次行動。不扣生命。",
 "throwables.stun":"射程 5、半徑 2。生物或有夜視／紅外線者中斷蓄勢並跳過 {turns} 次行動（通常含投擲當回合），頭目 {bossTurns} 次；恢復後免疫 {immunity} 次行動。會震暈自己，同樣 {turns} 次。",
 // src/traits.js
 "traits.suppression_resistance.name":"壓制抗性",
 "traits.suppression_resistance.text":"每階使單次所有來源合計的壓制層數 −1，最高 3 階。",
 "traits.rapid_fire.name":"連射",
 "traits.rapid_fire.text":"槍械攻擊多射 1 發，每發命中 −10；消耗實際發數的彈藥。",
 "traits.disruption_resistant.name":"抗失能",
 "traits.disruption_resistant.text":"受到的失能次數減半，向上取整。",
 "traits.poison_immunity.name":"毒無效",
 "traits.poison_immunity.text":"毒液噴吐、毒霧與污染液都不會讓你中毒，已有的中毒立即清除。污染液與高熱的直接傷害照常。",
 "traits.poison_resistance.name":"抗毒",
 "traits.poison_resistance.text":"中毒每回合傷害 −1；和密封防護的階數疊加。",
 "traits.tactical_supply.name":"戰術配給",
 "traits.tactical_supply.text":"每次升至 2～20 級時獲得 1 顆煙霧彈；共用投擲容量不足時留在腳下。滿級經驗補給不觸發。",
 "traits.extended_burst.name":"延伸點射",
 "traits.extended_burst.text":"僅衝鋒槍：原射程外再延伸 2 格，延伸區每次只射 1 發、消耗 1 發彈藥。射程詞條先計入原射程，兩發區與單發區一起順延。",
 "traits.difficult_healing.name":"難以治療",
 "traits.difficult_healing.text":"生命回復的基礎量減半，向下取整（醫療包、終端、升級、下樓、嗜血等）；急救訓練給醫療包的加成不減。不影響生命上限與護甲板。",
 "traits.extended_carry.name":"攜行擴充",
 "traits.extended_carry.text":"每種彈藥上限 +50%（四捨五入）、投擲物共用上限 +2、每種道具上限 +2。",
 "traits.night_vision.name":"夜視",
 "traits.night_vision.text":"忽略目標暗區的射擊命中懲罰；會受震撼彈失能，不穿煙。",
 "traits.exoskeleton.name":"外骨骼",
 "traits.exoskeleton.text":"射擊命中 +10、近戰傷害 +20%；自帶的護甲板打光時損毀，並被壓制 5 層。",
 "traits.infrared.name":"紅外線",
 "traits.infrared.text":"看穿煙霧，仍受牆與門阻擋；會受震撼彈失能，不抵銷暗區懲罰。",
 "traits.biological.name":"生物",
 "traits.biological.text":"會受到震撼彈的失能效果；可與機械同時存在。",
 "traits.mechanical.name":"機械",
 "traits.mechanical.text":"會受到 EMP 的失能效果，電漿直擊增傷 20%；可與生物同時存在。",
 "traits.heavy_armor.name":"重裝防護",
 "traits.heavy_armor.text":"直接傷害在固定裝甲後再減少 25%，向上取整；不抵擋環境或中毒。",
 "traits.cowering.name":"躲藏",
 "traits.cowering.text":"受傷過半，或在 4 格內親眼看到同伴被擊倒，就躲到最近的掩體後待命；打得到你才反擊。精英與機器不會躲。",
 "traits.payload_toxic.name":"毒霧囊",
 "traits.payload_toxic.text":"爆開時留下一團毒霧：不擋視線，接觸會中毒，槍彈與光束穿過時威力與命中減半，對蟲族無效。",
 "traits.payload_acid.name":"酸液囊",
 "traits.payload_acid.text":"爆開時在原地留下一格酸液。",
 "traits.payload_spore.name":"孢子囊",
 "traits.payload_spore.text":"爆開時留下一團孢子煙：擋住你這一方的視線，蟲族看得穿。",
 "traits.underfoot.name":"矮小",
 "traits.underfoot.text":"不擋任何直線位移（撲擊、鉤鎖、鉤舌、拉扯都能越過），但仍佔住自己那一格，不能落在牠身上。",
 "traits.lunge.name":"突進",
 "traits.lunge.text":"移動時沿路線一次衝過最多 3 格，只要那段是一條沒有被牆、障礙或其他單位擋住的直線。",
 "traits.detour.name":"迂迴",
 "traits.detour.text":"接近目標時走牠最後所知你看不到的路線（煙霧也算），最多多走約一個小房間外圍的距離；太遠就直接走最短路。",
 "traits.ready.name":"已就緒",
 "traits.ready.text":"小隊長下令後的一輪：受到的直接傷害減半、被射擊命中 −15、下一次射擊命中 +15。開火後由小隊長重新下令。",
 "traits.braced.name":"架槍",
 "traits.braced.text":"自己相對射擊目標受到掩體保護時，命中 +12。",
 "traits.correction.name":"著彈修正",
 "traits.correction.short":"修正",
 "traits.correction.text":"連續回合射擊同一敵人，後續命中每次 +8，最高 +24；未命中仍累積。",
 "traits.point_blank.name":"貼身射擊",
 "traits.point_blank.text":"3 格內射擊：忽略掩體與目標移動的命中懲罰，命中 +10。",
 "traits.sidestep.name":"側身",
 "traits.sidestep.text":"相對攻擊者主要橫向移動時，被射擊命中額外 −20；暴露時移動與側身合計至少 −42。",
 "traits.quick_reload.name":"快速裝填",
 "traits.quick_reload.short":"快填",
 "traits.quick_reload.text":"使用手槍彈的武器裝填不耗回合，仍消耗備彈。",
 "traits.large.name":"大型",
 "traits.large.text":"被射擊命中率 +15 個百分點。",
 "traits.small.name":"小型",
 "traits.small.text":"被射擊命中率 −15 個百分點。",
 "traits.agile.name":"敏捷",
 "traits.agile.text":"移動時，對手射擊命中率 −35（原為 −22）。",
 "traits.clumsy.name":"笨拙",
 "traits.clumsy.text":"移動時，對手射擊命中率 −9（原為 −22）。",
 "traits.no_cover.name":"無法利用掩體",
 "traits.no_cover.short":"無掩體",
 "traits.no_cover.text":"無法取得牆角／箱體的命中保護與減傷，牆壁仍阻擋視線。",
 "traits.fast.name":"快速",
 "traits.fast.text":"快速階段行動，每回合仍只有一次行動。",
 "traits.slow.name":"緩速",
 "traits.slow.text":"緩速階段行動；與快速同時存在時按普通速度結算。",
 "traits.bloodlust.name":"嗜血",
 "traits.bloodlust.text":"近戰造成的實際生命傷害，20% 回復為你的生命（不含溢出）。",
 "traits.battle_spirit.name":"戰意",
 "traits.battle_spirit.text":"近戰擊殺 +1 層、最多 5 層，每層受到的直接傷害 −5%；5 回合沒有近戰擊殺後，每 2 回合掉一層。",
 "traits.blade_stash.name":"刃藏",
 "traits.blade_stash.text":"背包每有一把近戰武器（含斧頭），所有攻擊傷害 +10%、受到的直接傷害 −10%。",
 "traits.ambush.name":"伏擊",
 "traits.ambush.text":"目標失能、目標或你站在煙霧中、目標還沒發現你，或你站在暗處時，近戰傷害 ×1.5；每次觸發讓光學迷彩冷卻 −1（迷彩生效中不減）。",
 "traits.duelist.name":"單挑",
 "traits.duelist.text":"只有一名已發現你的敵人看得到你時，射擊與近戰迴避 +15。",
 "traits.exposed.name":"標定",
 "traits.exposed.text":"被預警標定，暫時削弱對士兵的攻防。",
 "traits.label":"{name}{rank}{cancelled}",
 "traits.rank":" {n} 階",
 "traits.cancelled":"（抵銷）",
 // src/unarmed.js
 "unarmed.unarmed.name":"徒手",
 "unarmed.unarmed.code":"近戰",
 // 武器：名稱與說明（src/data.js）、詞條（src/weapons.js）
 "weapons.extendedBurst":" · 延伸點射：{range} 格內兩發，{from}–{to} 格單發",
 "weapons.rifle.name":"餘燼突擊步槍",
 "weapons.rifle.desc":"可靠的中距離主力，適合多數交戰。",
 "weapons.shotgun.name":"破門者霰彈槍",
 "weapons.shotgun.desc":"錐形射擊：一發打中錐形內所有目標（包含友軍），被前方單位擋住的打不到。每個目標依距離吃 6／6／5／4／3／2 顆彈丸（1～6 格），每顆 10–12、命中 95%，不受暗區與移動影響；裝甲每顆都扣，掩體減傷 60%。對掩體與門只打單一目標。",
 "weapons.smg.name":"蜂群衝鋒槍",
 "weapons.smg.desc":"每回合射擊兩發。適合清理近距離輕裝敵人。",
 "weapons.sniper.name":"寂靜精準步槍",
 "weapons.sniper.desc":"長距離單發重擊，穿透 70% 裝甲與掩體減傷。沒有先原地等待一回合瞄準時，命中 −40。",
 "weapons.plasma.name":"極光電漿步槍",
 "weapons.plasma.desc":"消耗能量電池。無視裝甲與掩體減傷（掩體仍會降低命中），對機械傷害 +20%。",
 "weapons.launcher.name":"日蝕榴彈發射器",
 "weapons.launcher.desc":"瞄準視線內一格地板發射，必定在落點爆炸，半徑 1 格。沒有最短射程，無視掩體，會傷害自己與引爆油桶。",
 "weapons.lmg.name":"堡壘輕機槍",
 "weapons.lmg.desc":"使用步槍彈，每次三連發，適合持續壓制。",
 "weapons.powerfist.name":"震擊動力拳",
 "weapons.powerfist.desc":"相鄰一格近戰，命中 99%，無限使用、無須裝填。無視掩體，穿透 50% 裝甲。裝甲內建，雙向切換免費；不能拆解或交換，可改裝至 +3。",
 "weapons.thunder.name":"雷鳴爆彈槍",
 "weapons.thunder.desc":"三連發爆彈，每發命中後爆炸半徑 1 格；會自傷及引爆油桶。使用榴彈彈藥，僅能探索拾取。",
 "weapons.axe.name":"狂戰斧",
 "weapons.axe.desc":"狂戰士綁定近戰武器，不能拆解或交換。相鄰一格，命中 92%，穿透 30% 裝甲，無限使用。",
 "weapons.katana.name":"忍刀",
 "weapons.katana.desc":"忍者綁定近戰武器，不能拆解或交換。相鄰一格，命中 95%，無限使用。",
 "weapons.lootMelee.desc":"拾獲近戰武器，雙向切換免費，可交換、拆解與改裝。",
 "weapons.knife.name":"求生小刀",
 "weapons.knife.desc":"比徒手準、也比徒手痛，換掉一格武器欄。撞上敵人時使用。",
 "weapons.claws.name":"手爪",
 "weapons.claws.desc":"快速段出手：在快速的敵人行動之前打到牠。目標沒有裝甲時傷害 ×1.5。",
 "weapons.sabre.name":"軍刀",
 "weapons.sabre.desc":"命中後，目標身旁看得見的其他敵人受到 45% 傷害。",
 "weapons.spear.name":"長矛",
 "weapons.spear.desc":"撞上敵人時照常近戰。拿在手上時可以開火：刺向 2 格內的目標，直線上每個單位各自判定命中，友軍也會被刺中；貼身時會刺穿到後面一格。",
 "weapons.chainsaw.name":"鏈鋸",
 "weapons.chainsaw.desc":"緩速段出手：普通敵人先行動。命中後連鋸 10 下，每下 3–10、無視裝甲；命中後你會跳過下一次行動。",
 "weapons.noAffix":"標準型，沒有詞條",
 "weapons.unlimited":"無限使用",
 "weapons.affixedName":"{affix}・{weapon}",
 "weapons.mastery":" · 改裝精通：好處 +{n}%",
 // winCopy
 "winCopy.title":"火種已熄滅。",
 "winCopy.body":"設施目標已達成。交戰紀錄已提交評估。",
 // src/workshop.js
 "workshop.queuedPayload":"與 1 顆{grenade}",
 "workshop.queuedWeapon":"（{weapon}）",
 "workshop.deployedPayload":"（{grenade}）",
 "workshop.blueprintMissing":"尚未取得藍圖：擊毀{enemy}後取得。",
 "workshop.scrapShort":"廢料不足，需要 {n}。",
 "workshop.noPayload":"沒有{item}。",
 "workshop.queued":"消耗 {cost} 廢料{payload}，{unit}{weapon}已放進生產序列。",
 "workshop.deployCap":"部署上限 {n} 台已滿。",
 "workshop.allyCapLost":"友軍名額已滿：留在第 {floor} 層的{ally}已失去連線。",
 "workshop.weaponDropped":"{weapon}掉在{ally}的位置。",
 "workshop.deployed":"{ally}{payload}已部署。",
 "workshop.undamaged":"{ally}沒有損傷。",
 "workshop.repaired":"消耗 {cost} 廢料修理{ally}，生命 +{n}（{hp}/{max}）。",
 "workshop.munitionDive":"浮游彈藥俯衝引爆{grenade}。",
 "workshop.blueprint":"取得藍圖：{unit}。打開工坊就能生產。",
});
